import { useEffect, useMemo, useState } from "react";
import { formatTokenCount } from "@shared/token-estimate";
import { useTranslation } from "react-i18next";
import { Loader2Icon } from "lucide-react";
import { cn } from "@/lib/utils";
import { useDocumentStore } from "@/stores/document-store";
import {
  SETTINGS_CATEGORY_HEADER,
  SETTINGS_DETAIL_SHELL,
  SETTINGS_ROW_DESC,
} from "./settings-tokens";
import { PromptInternalsNotice } from "./prompt-internals-notice";
import { SettingsModulePromptPreview } from "./settings-module-prompt-preview";

const BADGE =
  "inline-flex items-center rounded px-1.5 py-0.5 text-[length:var(--font-size-10)] font-medium uppercase tracking-wide shrink-0";

type KnowledgeModuleInfo = Awaited<
  ReturnType<typeof window.electronAPI.settingsGetKnowledgeModules>
>[number];

function ModuleCard({ mod }: { mod: KnowledgeModuleInfo }) {
  const { t } = useTranslation();
  return (
    <article className="rounded-lg border border-border px-4 py-3 space-y-2">
      <div className="flex flex-wrap items-center gap-2">
        <p className="text-[length:var(--font-size-13)] font-medium">{mod.label}</p>
        <code className="text-[length:var(--font-size-11)] text-muted-foreground">{mod.key}</code>
        <span className="text-[length:var(--font-size-11)] text-muted-foreground/70 tabular-nums">
          {t("settings.editor.promptStack.tokens", {
            count: formatTokenCount(mod.tokenCount),
          })}
        </span>
        {mod.autoGenerated ? (
          <span className={cn(BADGE, "bg-primary/10 text-primary")}>
            {t("settings.editor.knowledge.badgeAuto")}
          </span>
        ) : (
          <span className={cn(BADGE, "bg-muted text-muted-foreground")}>
            {t("settings.editor.knowledge.badgeBuiltin")}
          </span>
        )}
        {mod.selectableInProfile ? (
          <span className={cn(BADGE, "bg-muted text-muted-foreground normal-case tracking-normal")}>
            {t("settings.editor.knowledge.badgePerAgent")}
          </span>
        ) : (
          <span className={cn(BADGE, "bg-muted text-muted-foreground normal-case tracking-normal")}>
            {t("settings.editor.knowledge.badgeAlwaysOn")}
          </span>
        )}
      </div>
      <p className={SETTINGS_ROW_DESC}>{mod.description}</p>
      <p className="text-[length:var(--font-size-11)] text-muted-foreground/80">
        {t("settings.editor.knowledge.injectedVia")} {mod.injectPath}
      </p>
      {mod.contentPreview ? <SettingsModulePromptPreview content={mod.contentPreview} /> : null}
    </article>
  );
}

export function KnowledgeModulesPanel() {
  const { t } = useTranslation();
  const projectRoot = useDocumentStore((s) => s.projectRoot);
  const [modules, setModules] = useState<KnowledgeModuleInfo[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    let cancelled = false;
    void window.electronAPI
      .settingsGetKnowledgeModules(projectRoot ?? undefined)
      .then((list) => {
        if (!cancelled) setModules(list);
      })
      .catch(() => {
        if (!cancelled) setModules([]);
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, [projectRoot]);

  const grouped = useMemo(() => {
    const global = modules.filter((m) => !m.profileOnly);
    const profile = modules.filter((m) => m.profileOnly);
    return { global, profile };
  }, [modules]);

  if (loading) {
    return (
      <div className="flex flex-1 items-center justify-center text-muted-foreground">
        <Loader2Icon className="size-5 animate-spin" />
      </div>
    );
  }

  return (
    <div className={SETTINGS_DETAIL_SHELL}>
      <div className="space-y-3">
        <div className="space-y-1">
          <h2 className="text-[length:var(--font-size-15)] font-semibold">{t("settings.editor.knowledge.title")}</h2>
          <p className={SETTINGS_ROW_DESC}>{t("settings.editor.knowledge.intro")}</p>
        </div>
        <PromptInternalsNotice />
      </div>

      {grouped.global.length > 0 ? (
        <section className="space-y-3">
          <h3 className={SETTINGS_CATEGORY_HEADER}>{t("settings.editor.knowledge.global")}</h3>
          <div className="space-y-3">
            {grouped.global.map((mod) => (
              <ModuleCard key={mod.key} mod={mod} />
            ))}
          </div>
        </section>
      ) : null}

      {grouped.profile.length > 0 ? (
        <section className="space-y-3">
          <h3 className={SETTINGS_CATEGORY_HEADER}>{t("settings.editor.knowledge.perProfile")}</h3>
          <div className="space-y-3">
            {grouped.profile.map((mod) => (
              <ModuleCard key={mod.key} mod={mod} />
            ))}
          </div>
        </section>
      ) : null}
    </div>
  );
}
