import { useState, useEffect, useCallback } from "react";
import { useSettingsStore } from "@/stores/settings-store";
import { useDocumentStore } from "@/stores/document-store";
import { openSettingsPanel } from "@/stores/settings-panel-store";
import { useOnSettingsEditorKindsClosed } from "@/hooks/use-settings-editor";
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";
import { cn } from "@/lib/utils";
import { useInlineDeleteConfirm } from "@/hooks/use-inline-delete-confirm";
import { InlineDeleteButton } from "./inline-delete-button";
import { notifyPromptConfigChanged } from "@/lib/settings/prompt-config-notify";

const CATEGORY_HEADER =
  "text-[length:var(--font-size-12)] font-semibold uppercase tracking-wider text-muted-foreground/60 mb-1";
const CARD = "rounded-lg border border-border px-4 divide-y divide-border";
const ROW = "flex items-center justify-between py-2.5 group";
/** Prompt rows: wrap action buttons below text when the panel is narrow. */
const PROMPT_ROW = "flex flex-wrap items-start justify-between gap-x-4 gap-y-2 py-2.5";
const PROMPT_ROW_BODY = "min-w-0 flex-1 basis-[min(100%,12rem)]";
const PROMPT_ROW_ACTIONS = "flex flex-wrap items-center gap-2 shrink-0 ml-auto";
const ROW_LABEL = "text-[length:var(--font-size-13)] font-medium";
const ROW_DESC = "text-[length:var(--font-size-12)] text-muted-foreground mt-0.5";
const BADGE =
  "inline-flex items-center rounded px-1.5 py-0.5 text-[length:var(--font-size-10)] font-medium uppercase tracking-wide";

interface ModuleInfo {
  key: string;
  label: string;
  description: string;
  enabled: boolean;
  autoGenerated?: boolean;
}

function KnowledgeModulesSection({ onRefresh }: { onRefresh: () => void }) {
  const [modules, setModules] = useState<ModuleInfo[]>([]);
  const [loading, setLoading] = useState(true);

  const loadModules = useCallback(async () => {
    try {
      const mods = await window.electronAPI.settingsGetModules();
      setModules(mods);
    } catch {
      /* ignore */
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    loadModules();
  }, [loadModules]);

  const handleModuleToggle = async (key: string, enabled: boolean) => {
    setModules((prev) => prev.map((m) => (m.key === key ? { ...m, enabled } : m)));
    try {
      await window.electronAPI.settingsSetModule(key, enabled);
      onRefresh();
      notifyPromptConfigChanged();
    } catch {
      setModules((prev) => prev.map((m) => (m.key === key ? { ...m, enabled: !enabled } : m)));
    }
  };

  return (
    <div className={CARD}>
      {loading ? (
        <div className={cn(ROW, "!block")}>
          <p className="text-[length:var(--font-size-12)] text-muted-foreground">Loading…</p>
        </div>
      ) : (
        modules.map((mod) => (
          <div key={mod.key} className={ROW}>
            <div className="min-w-0 flex-1 pr-4">
              <div className="flex items-center gap-2">
                <p className={ROW_LABEL}>{mod.label}</p>
                {mod.autoGenerated ? (
                  <span className={cn(BADGE, "bg-primary/10 text-primary")}>Auto</span>
                ) : (
                  <span className={cn(BADGE, "bg-muted text-muted-foreground")}>Built-in</span>
                )}
              </div>
              <p className={ROW_DESC}>{mod.description}</p>
            </div>
            <Switch checked={mod.enabled} onCheckedChange={(v) => handleModuleToggle(mod.key, v)} />
          </div>
        ))
      )}
    </div>
  );
}

function ProjectRulesSection() {
  const projectRoot = useDocumentStore((s) => s.projectRoot);
  const [rules, setRules] = useState<
    Awaited<ReturnType<typeof window.electronAPI.agentListRules>>
  >([]);
  const [busy, setBusy] = useState(false);
  const deleteConfirm = useInlineDeleteConfirm();

  const loadRules = useCallback(async () => {
    if (!projectRoot) {
      setRules([]);
      return;
    }
    try {
      setRules(await window.electronAPI.agentListRules(projectRoot));
    } catch {
      setRules([]);
    }
  }, [projectRoot]);

  useEffect(() => {
    void loadRules();
  }, [loadRules]);

  useOnSettingsEditorKindsClosed(["rule-markdown"], () => {
    void loadRules();
  });

  const handleToggleRule = async (id: string, enabled: boolean) => {
    if (!projectRoot) return;
    deleteConfirm.clearPending();
    setRules((prev) => prev.map((r) => (r.id === id ? { ...r, enabled } : r)));
    setBusy(true);
    try {
      await window.electronAPI.agentSetRuleEnabled(projectRoot, id, enabled);
      notifyPromptConfigChanged();
    } catch {
      await loadRules();
    } finally {
      setBusy(false);
    }
  };

  const confirmDelete = async (id: string) => {
    if (!projectRoot) return;
    deleteConfirm.clearPending();
    setBusy(true);
    try {
      await window.electronAPI.agentDeleteRule(projectRoot, id);
      setRules((prev) => prev.filter((r) => r.id !== id));
      notifyPromptConfigChanged();
    } finally {
      setBusy(false);
    }
  };

  const openRule = (rule: (typeof rules)[number]) => {
    deleteConfirm.clearPending();
    openSettingsPanel({
      kind: "rule-markdown",
      mode: "edit",
      ruleId: rule.id,
      title: rule.name,
    });
  };

  if (!projectRoot) {
    return (
      <div className={CARD}>
        <div className={cn(ROW, "!block")}>
          <p className="text-[length:var(--font-size-12)] text-muted-foreground">
            Open a project to manage project rules.
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className={CARD}>
      {rules.length === 0 ? (
        <div className={cn(ROW, "!block")}>
          <p className="text-[length:var(--font-size-12)] text-muted-foreground">No project rules yet.</p>
        </div>
      ) : (
        rules.map((rule) => (
          <div key={rule.id} className={ROW}>
            <button
              type="button"
              className="min-w-0 flex-1 pr-4 text-left"
              onClick={() => openRule(rule)}
            >
              <div className="flex items-center gap-2">
                <p className={ROW_LABEL}>{rule.name}</p>
                <span className={cn(BADGE, "bg-muted text-muted-foreground")}>Custom</span>
              </div>
              <p className={cn(ROW_DESC, "truncate")}>
                {rule.description || "No description."}
              </p>
            </button>
            <div className="flex items-center gap-1 shrink-0">
              <Button variant="ghost" size="xs" disabled={busy} onClick={() => openRule(rule)}>
                Edit
              </Button>
              <Switch
                checked={rule.enabled}
                onCheckedChange={(v) => void handleToggleRule(rule.id, v)}
              />
              <InlineDeleteButton
                itemId={rule.id}
                pending={deleteConfirm.isPending(rule.id)}
                disabled={busy}
                stopPropagation
                onRequest={() => deleteConfirm.setPendingId(rule.id)}
                onConfirm={() => void confirmDelete(rule.id)}
              />
            </div>
          </div>
        ))
      )}
      <div className="py-2.5">
        <Button
          variant="ghost"
          size="xs"
          onClick={() => openSettingsPanel({ kind: "rule-markdown", mode: "new" })}
        >
          + Add project rule
        </Button>
      </div>
    </div>
  );
}

export function PromptsRulesSettings() {
  const agentSystemPrompt = useSettingsStore((s) => s.settings.agentSystemPrompt) ?? "";
  const projectRoot = useDocumentStore((s) => s.projectRoot);

  const isCustom = agentSystemPrompt.trim().length > 0;
  const [assembledLength, setAssembledLength] = useState(0);
  const [agentsMdLength, setAgentsMdLength] = useState(0);
  const [hasAgentsMd, setHasAgentsMd] = useState(false);

  const agentsMdPath = projectRoot
    ? `${projectRoot.replace(/[/\\]+$/, "")}/.prismnext/agent/AGENTS.md`
    : "";

  const refreshSummaries = useCallback(async () => {
    try {
      const assembled = await window.electronAPI.settingsGetAssembledPrompt(
        projectRoot ?? undefined,
        agentSystemPrompt || undefined,
      );
      setAssembledLength(assembled?.length ?? 0);
    } catch {
      setAssembledLength(0);
    }

    if (!projectRoot) {
      setAgentsMdLength(0);
      setHasAgentsMd(false);
      return;
    }
    try {
      const exists = await window.electronAPI.fsExists(agentsMdPath);
      if (!exists) {
        setAgentsMdLength(0);
        setHasAgentsMd(false);
        return;
      }
      const r = await window.electronAPI.fsRead(agentsMdPath);
      const content = r?.content || "";
      setAgentsMdLength(content.length);
      setHasAgentsMd(content.trim().length > 0);
    } catch {
      setAgentsMdLength(0);
      setHasAgentsMd(false);
    }
  }, [projectRoot, agentSystemPrompt, agentsMdPath]);

  useEffect(() => {
    void refreshSummaries();
  }, [refreshSummaries]);

  useOnSettingsEditorKindsClosed(["prompt-markdown", "rule-markdown"], () => {
    void refreshSummaries();
  });

  const openSystemPrompt = () => {
    openSettingsPanel({ kind: "prompt-markdown", doc: "system-prompt" });
  };

  return (
    <div className="flex-1 overflow-auto">
      <div className="max-w-3xl mx-auto px-8 py-8 space-y-8">
        <div>
          <h2 className="text-[length:var(--font-dialog-title)] font-semibold">Prompts &amp; Rules</h2>
          <p className="text-[length:var(--font-dialog-label)] text-muted-foreground mt-0.5">
            System prompt, project instructions, knowledge modules, and project rules.
          </p>
        </div>

        <div>
          <h3 className={CATEGORY_HEADER}>Prompts</h3>
          <p className="text-[length:var(--font-size-12)] text-muted-foreground mb-2">
            System prompt and per-project instructions injected on every chat.
          </p>
          <div className={CARD}>
            <div className={PROMPT_ROW}>
              <div className={PROMPT_ROW_BODY}>
                <div className="flex flex-wrap items-center gap-2">
                  <p className={ROW_LABEL}>System prompt</p>
                  {isCustom ? (
                    <span className={cn(BADGE, "bg-primary/10 text-primary normal-case tracking-normal")}>
                      Custom
                    </span>
                  ) : null}
                </div>
                <p className={ROW_DESC}>
                  {isCustom
                    ? "Custom prompt replaces the built-in default. Modules and AGENTS.md load as separate system instructions."
                    : "Using the built-in Prism editor prompt. Write a custom prompt to override it."}
                </p>
                <p className="text-[length:var(--font-size-11)] text-muted-foreground/70 mt-0.5">
                  {assembledLength > 0
                    ? `${assembledLength.toLocaleString()} characters in the assembled system prompt.`
                    : "No prompt assembled yet."}
                </p>
              </div>
              <div className={PROMPT_ROW_ACTIONS}>
                <Button variant="ghost" size="xs" className="shrink-0" onClick={openSystemPrompt}>
                  {isCustom ? "View & edit prompt" : "Custom prompt"}
                </Button>
                <Button
                  variant="ghost"
                  size="xs"
                  className="shrink-0"
                  disabled={assembledLength === 0}
                  onClick={() =>
                    openSettingsPanel({ kind: "prompt-markdown", doc: "assembled" })
                  }
                >
                  Preview prompt
                </Button>
              </div>
            </div>

            <div className={PROMPT_ROW}>
              <div className={PROMPT_ROW_BODY}>
                <p className={ROW_LABEL}>Project instructions</p>
                {!projectRoot ? (
                  <p className={ROW_DESC}>Open a project to edit project instructions.</p>
                ) : (
                  <>
                    <p className={ROW_DESC}>
                      Per-project instructions from{" "}
                      <code className="text-[length:var(--font-size-11)] bg-muted px-1 py-0.5 rounded">
                        .prismnext/agent/AGENTS.md
                      </code>
                      . Run{" "}
                      <code className="text-[length:var(--font-size-11)] bg-muted px-1 py-0.5 rounded">
                        /setup
                      </code>{" "}
                      in chat to scaffold from the project.
                    </p>
                    <p className="text-[length:var(--font-size-11)] text-muted-foreground/70 mt-0.5">
                      {hasAgentsMd
                        ? `${agentsMdLength.toLocaleString()} characters in project instructions.`
                        : "No AGENTS.md yet — create one or run /setup in chat."}
                    </p>
                  </>
                )}
              </div>
              {projectRoot ? (
                <div className={PROMPT_ROW_ACTIONS}>
                  <Button
                    variant="ghost"
                    size="xs"
                    className="shrink-0"
                    onClick={() =>
                      openSettingsPanel({ kind: "prompt-markdown", doc: "agents-md" })
                    }
                  >
                    {hasAgentsMd ? "Edit instructions" : "Create AGENTS.md"}
                  </Button>
                </div>
              ) : null}
            </div>
          </div>
        </div>

        <div>
          <h3 className={CATEGORY_HEADER}>Knowledge Modules</h3>
          <p className="text-[length:var(--font-size-12)] text-muted-foreground mb-2">
            LaTeX and writing knowledge injected via the system prompt. Agent profiles only use
            modules enabled here.
          </p>
          <KnowledgeModulesSection onRefresh={() => void refreshSummaries()} />
        </div>

        <div>
          <h3 className={CATEGORY_HEADER}>Agent Tools</h3>
          <p className="text-[length:var(--font-size-12)] text-muted-foreground mb-2">
            Built-in OpenCode tools. Usage hints sync into each tool&apos;s schema description on
            startup — not knowledge modules.
          </p>
          <div className={CARD}>
            <div className={ROW}>
              <div className="min-w-0 flex-1 pr-4">
                <p className={ROW_LABEL}>Built-in tools</p>
                <p className={ROW_DESC}>
                  View all registered tools and the descriptions the model sees when choosing tools.
                </p>
              </div>
              <Button
                variant="ghost"
                size="xs"
                className="shrink-0"
                onClick={() => openSettingsPanel({ kind: "agent-tools" })}
              >
                View tools
              </Button>
            </div>
          </div>
        </div>

        <div>
          <h3 className={CATEGORY_HEADER}>Project Rules</h3>
          <p className="text-[length:var(--font-size-12)] text-muted-foreground mb-2">
            Additional per-project rules stored in{" "}
            <code className="text-[length:var(--font-size-11)] bg-muted px-1 py-0.5 rounded">
              .prismnext/agent/rules/&lt;id&gt;/RULE.md
            </code>
          </p>
          <ProjectRulesSection />
        </div>
      </div>
    </div>
  );
}
