import katex from "katex";

export interface LaTeXSymbol {
  /** The LaTeX command inserted when the symbol is clicked. */
  command: string;
  /** Override what KaTeX renders. Defaults to `command` if omitted.
   *  Use this when the inserted command can't be rendered standalone
   *  (e.g. \textsterling → render as \text{£}). */
  renderAs?: string;
  /** Fallback display character (used if KaTeX render fails). */
  display: string;
}

export interface SymbolCategory {
  label: string;
  symbols: LaTeXSymbol[];
}

// ─── Pre-render cache ───

const _htmlCache = new Map<string, string>();

function cacheKey(sym: LaTeXSymbol): string {
  return sym.renderAs ?? sym.command;
}

/** Render a LaTeX symbol to HTML via KaTeX. Uses `renderAs` if provided,
 *  otherwise falls back to `command`. Results are cached — calling with
 *  the same symbol returns the pre-rendered HTML instantly. */
export function getSymbolHtml(sym: LaTeXSymbol): string {
  const cmd = sym.renderAs ?? sym.command;
  const cached = _htmlCache.get(cmd);
  if (cached !== undefined) return cached;

  try {
    const html = katex.renderToString(cmd, {
      throwOnError: false,
      displayMode: false,
      strict: false,
    });
    // KaTeX with throwOnError:false renders error spans for unsupported commands.
    // Detect and treat as failure so we fall back to the display character.
    if (html.includes("katex-error")) {
      _htmlCache.set(cmd, "");
      return "";
    }
    _htmlCache.set(cmd, html);
    return html;
  } catch {
    _htmlCache.set(cmd, "");
    return "";
  }
}

/** Pre-render all symbols in all categories. Call once (e.g. on idle callback
 *  or on first Popover open) to avoid jank during scroll. */
export function preRenderAllSymbols(): void {
  for (const cat of SYMBOL_CATEGORIES) {
    for (const sym of cat.symbols) {
      getSymbolHtml(sym);
    }
  }
}

export const SYMBOL_CATEGORIES: SymbolCategory[] = [
  {
    label: "Greek Lowercase",
    symbols: [
      { command: "\\alpha", display: "α" },
      { command: "\\beta", display: "β" },
      { command: "\\gamma", display: "γ" },
      { command: "\\delta", display: "δ" },
      { command: "\\epsilon", display: "ϵ" },
      { command: "\\varepsilon", display: "ε" },
      { command: "\\zeta", display: "ζ" },
      { command: "\\eta", display: "η" },
      { command: "\\theta", display: "θ" },
      { command: "\\vartheta", display: "ϑ" },
      { command: "\\iota", display: "ι" },
      { command: "\\kappa", display: "κ" },
      { command: "\\varkappa", display: "ϰ" },
      { command: "\\lambda", display: "λ" },
      { command: "\\mu", display: "μ" },
      { command: "\\nu", display: "ν" },
      { command: "\\xi", display: "ξ" },
      { command: "\\pi", display: "π" },
      { command: "\\varpi", display: "ϖ" },
      { command: "\\rho", display: "ρ" },
      { command: "\\varrho", display: "ϱ" },
      { command: "\\sigma", display: "σ" },
      { command: "\\varsigma", display: "ς" },
      { command: "\\tau", display: "τ" },
      { command: "\\upsilon", display: "υ" },
      { command: "\\phi", display: "φ" },
      { command: "\\varphi", display: "ϕ" },
      { command: "\\chi", display: "χ" },
      { command: "\\psi", display: "ψ" },
      { command: "\\omega", display: "ω" },
      { command: "\\digamma", display: "ϝ" },
    ],
  },
  {
    label: "Greek Uppercase",
    symbols: [
      { command: "\\Gamma", display: "Γ" },
      { command: "\\Delta", display: "Δ" },
      { command: "\\Theta", display: "Θ" },
      { command: "\\Lambda", display: "Λ" },
      { command: "\\Xi", display: "Ξ" },
      { command: "\\Pi", display: "Π" },
      { command: "\\Sigma", display: "Σ" },
      { command: "\\Upsilon", display: "Υ" },
      { command: "\\Phi", display: "Φ" },
      { command: "\\Psi", display: "Ψ" },
      { command: "\\Omega", display: "Ω" },
      { command: "\\varGamma", display: "Γ" },
      { command: "\\varDelta", display: "Δ" },
      { command: "\\varTheta", display: "Θ" },
      { command: "\\varLambda", display: "Λ" },
      { command: "\\varXi", display: "Ξ" },
      { command: "\\varPi", display: "Π" },
      { command: "\\varSigma", display: "Σ" },
      { command: "\\varUpsilon", display: "Υ" },
      { command: "\\varPhi", display: "Φ" },
      { command: "\\varPsi", display: "Ψ" },
      { command: "\\varOmega", display: "Ω" },
    ],
  },
  {
    label: "Binary Operators",
    symbols: [
      { command: "\\pm", display: "±" },
      { command: "\\mp", display: "∓" },
      { command: "\\times", display: "×" },
      { command: "\\div", display: "÷" },
      { command: "\\cdot", display: "·" },
      { command: "\\ast", display: "∗" },
      { command: "\\star", display: "⋆" },
      { command: "\\circ", display: "∘" },
      { command: "\\bullet", display: "•" },
      { command: "\\diamond", display: "⋄" },
      { command: "\\cap", display: "∩" },
      { command: "\\cup", display: "∪" },
      { command: "\\uplus", display: "⊎" },
      { command: "\\sqcap", display: "⊓" },
      { command: "\\sqcup", display: "⊔" },
      { command: "\\wedge", display: "∧" },
      { command: "\\vee", display: "∨" },
      { command: "\\oplus", display: "⊕" },
      { command: "\\ominus", display: "⊖" },
      { command: "\\otimes", display: "⊗" },
      { command: "\\oslash", display: "⊘" },
      { command: "\\odot", display: "⊙" },
      { command: "\\bigcirc", display: "◯" },
      { command: "\\bigtriangleup", display: "△" },
      { command: "\\bigtriangledown", display: "▽" },
      { command: "\\triangleleft", display: "◃" },
      { command: "\\triangleright", display: "▹" },
      { command: "\\setminus", display: "∖" },
      { command: "\\wr", display: "≀" },
      { command: "\\amalg", display: "⨿" },
      { command: "\\dagger", display: "†" },
      { command: "\\ddagger", display: "‡" },
      { command: "\\lhd", display: "⊲" },
      { command: "\\rhd", display: "⊳" },
      { command: "\\unlhd", display: "⊴" },
      { command: "\\unrhd", display: "⊵" },
      { command: "\\dotplus", display: "∔" },
      { command: "\\centerdot", display: "⊙" },
      { command: "\\ltimes", display: "⋉" },
      { command: "\\rtimes", display: "⋊" },
      { command: "\\leftthreetimes", display: "⋋" },
      { command: "\\rightthreetimes", display: "⋌" },
      { command: "\\curlyvee", display: "⋎" },
      { command: "\\curlywedge", display: "⋏" },
      { command: "\\veebar", display: "⊻" },
      { command: "\\barwedge", display: "⊼" },
      { command: "\\doublebarwedge", display: "⩞" },
      { command: "\\circleddash", display: "⊝" },
      { command: "\\circledcirc", display: "⊚" },
      { command: "\\circledast", display: "⊛" },
      { command: "\\boxplus", display: "⊞" },
      { command: "\\boxminus", display: "⊟" },
      { command: "\\boxtimes", display: "⊠" },
      { command: "\\boxdot", display: "⊡" },
      { command: "\\divideontimes", display: "⋇" },
      { command: "\\intercal", display: "⊺" },
      { command: "\\Cap", display: "⋒" },
      { command: "\\Cup", display: "⋓" },
    ],
  },
  {
    label: "Relations",
    symbols: [
      { command: "\\leq", display: "≤" },
      { command: "\\geq", display: "≥" },
      { command: "\\neq", display: "≠" },
      { command: "\\equiv", display: "≡" },
      { command: "\\approx", display: "≈" },
      { command: "\\simeq", display: "≃" },
      { command: "\\cong", display: "≅" },
      { command: "\\sim", display: "∼" },
      { command: "\\propto", display: "∝" },
      { command: "\\doteq", display: "≐" },
      { command: "\\ll", display: "≪" },
      { command: "\\gg", display: "≫" },
      { command: "\\prec", display: "≺" },
      { command: "\\succ", display: "≻" },
      { command: "\\preceq", display: "≼" },
      { command: "\\succeq", display: "≽" },
      { command: "\\subset", display: "⊂" },
      { command: "\\supset", display: "⊃" },
      { command: "\\subseteq", display: "⊆" },
      { command: "\\supseteq", display: "⊇" },
      { command: "\\sqsubseteq", display: "⊑" },
      { command: "\\sqsupseteq", display: "⊒" },
      { command: "\\in", display: "∈" },
      { command: "\\notin", display: "∉" },
      { command: "\\ni", display: "∋" },
      { command: "\\vdash", display: "⊢" },
      { command: "\\dashv", display: "⊣" },
      { command: "\\models", display: "⊧" },
      { command: "\\mid", display: "∣" },
      { command: "\\parallel", display: "∥" },
      { command: "\\perp", display: "⊥" },
      { command: "\\smile", display: "⌣" },
      { command: "\\frown", display: "⌢" },
      { command: "\\bowtie", display: "⋈" },
      { command: "\\asymp", display: "≍" },
      { command: "\\doteqdot", display: "≑" },
      { command: "\\fallingdotseq", display: "≒" },
      { command: "\\risingdotseq", display: "≓" },
      { command: "\\bumpeq", display: "≏" },
      { command: "\\Bumpeq", display: "≎" },
      { command: "\\between", display: "≬" },
      { command: "\\pitchfork", display: "⋔" },
      { command: "\\vartriangle", display: "△" },
      { command: "\\triangledown", display: "▽" },
      { command: "\\trianglelefteq", display: "⊴" },
      { command: "\\trianglerighteq", display: "⊵" },
      { command: "\\vDash", display: "⊨" },
      { command: "\\Vvdash", display: "⊪" },
      { command: "\\Vdash", display: "⊩" },
      { command: "\\therefore", display: "∴" },
      { command: "\\because", display: "∵" },
      { command: "\\eqcirc", display: "≖" },
      { command: "\\circeq", display: "≗" },
      { command: "\\thickapprox", display: "≈" },
      { command: "\\thicksim", display: "∼" },
      { command: "\\succapprox", display: "⪸" },
      { command: "\\precapprox", display: "⪷" },
      { command: "\\succsim", display: "≿" },
      { command: "\\precsim", display: "≾" },
      { command: "\\curlyeqprec", display: "⋞" },
      { command: "\\curlyeqsucc", display: "⋟" },
      { command: "\\preccurlyeq", display: "≼" },
      { command: "\\succcurlyeq", display: "≽" },
      { command: "\\subseteqq", display: "⫅" },
      { command: "\\supseteqq", display: "⫆" },
      { command: "\\Subset", display: "⋐" },
      { command: "\\Supset", display: "⋑" },
      { command: "\\sqsubset", display: "⊏" },
      { command: "\\sqsupset", display: "⊐" },
      { command: "\\vartriangleleft", display: "⊲" },
      { command: "\\vartriangleright", display: "⊳" },
      { command: "\\triangleq", display: "≜" },
      { command: "\\varpropto", display: "∝" },
      { command: "\\backsimeq", display: "⋍" },
      { command: "\\backepsilon", display: "϶" },
      { command: "\\eqslantless", display: "⪕" },
      { command: "\\eqslantgtr", display: "⪖" },
      { command: "\\gtrsim", display: "≳" },
      { command: "\\lesssim", display: "≲" },
      { command: "\\gtrapprox", display: "⪆" },
      { command: "\\lessapprox", display: "⪅" },
      { command: "\\smallsmile", display: "⌣" },
      { command: "\\smallfrown", display: "⌢" },
    ],
  },
  {
    label: "Negated Relations",
    symbols: [
      { command: "\\nless", display: "≮" },
      { command: "\\ngtr", display: "≯" },
      { command: "\\nleq", display: "≰" },
      { command: "\\ngeq", display: "≱" },
      { command: "\\nleqslant", display: "⩽̸" },
      { command: "\\ngeqslant", display: "⩾̸" },
      { command: "\\nleqq", display: "≰" },
      { command: "\\ngeqq", display: "≱" },
      { command: "\\lneq", display: "⪇" },
      { command: "\\gneq", display: "⪈" },
      { command: "\\lneqq", display: "≨" },
      { command: "\\gneqq", display: "≩" },
      { command: "\\lvertneqq", display: "≨" },
      { command: "\\gvertneqq", display: "≩" },
      { command: "\\lnsim", display: "⋦" },
      { command: "\\gnsim", display: "⋧" },
      { command: "\\lnapprox", display: "⪉" },
      { command: "\\gnapprox", display: "⪊" },
      { command: "\\nprec", display: "⊀" },
      { command: "\\nsucc", display: "⊁" },
      { command: "\\npreceq", display: "⋠" },
      { command: "\\nsucceq", display: "⋡" },
      { command: "\\precneqq", display: "⪵" },
      { command: "\\succneqq", display: "⪶" },
      { command: "\\precnsim", display: "⋨" },
      { command: "\\succnsim", display: "⋩" },
      { command: "\\subsetneq", display: "⊊" },
      { command: "\\supsetneq", display: "⊋" },
      { command: "\\subsetneqq", display: "⫋" },
      { command: "\\supsetneqq", display: "⫌" },
      { command: "\\nsubseteq", display: "⊈" },
      { command: "\\nsupseteq", display: "⊉" },
      { command: "\\nsubseteqq", display: "⊈" },
      { command: "\\nsupseteqq", display: "⊉" },
      { command: "\\nsim", display: "≁" },
      { command: "\\ncong", display: "≇" },
      { command: "\\nvdash", display: "⊬" },
      { command: "\\nvDash", display: "⊭" },
      { command: "\\nVdash", display: "⊮" },
      { command: "\\nVDash", display: "⊯" },
      { command: "\\nmid", display: "∤" },
      { command: "\\nparallel", display: "∦" },
      { command: "\\nshortmid", display: "∤" },
      { command: "\\nshortparallel", display: "∦" },
    ],
  },
  {
    label: "Arrows",
    symbols: [
      { command: "\\leftarrow", display: "←" },
      { command: "\\rightarrow", display: "→" },
      { command: "\\leftrightarrow", display: "↔" },
      { command: "\\Leftarrow", display: "⇐" },
      { command: "\\Rightarrow", display: "⇒" },
      { command: "\\Leftrightarrow", display: "⇔" },
      { command: "\\longleftarrow", display: "⟵" },
      { command: "\\longrightarrow", display: "⟶" },
      { command: "\\longleftrightarrow", display: "⟷" },
      { command: "\\Longleftarrow", display: "⟸" },
      { command: "\\Longrightarrow", display: "⟹" },
      { command: "\\Longleftrightarrow", display: "⟺" },
      { command: "\\mapsto", display: "↦" },
      { command: "\\longmapsto", display: "⟼" },
      { command: "\\hookleftarrow", display: "↩" },
      { command: "\\hookrightarrow", display: "↪" },
      { command: "\\rightharpoonup", display: "⇀" },
      { command: "\\rightharpoondown", display: "⇁" },
      { command: "\\leftharpoonup", display: "↼" },
      { command: "\\leftharpoondown", display: "↽" },
      { command: "\\rightleftharpoons", display: "⇌" },
      { command: "\\leftrightharpoons", display: "⇋" },
      { command: "\\uparrow", display: "↑" },
      { command: "\\downarrow", display: "↓" },
      { command: "\\updownarrow", display: "↕" },
      { command: "\\Uparrow", display: "⇑" },
      { command: "\\Downarrow", display: "⇓" },
      { command: "\\Updownarrow", display: "⇕" },
      { command: "\\nearrow", display: "↗" },
      { command: "\\searrow", display: "↘" },
      { command: "\\swarrow", display: "↙" },
      { command: "\\nwarrow", display: "↖" },
      { command: "\\leadsto", display: "↝" },
      { command: "\\leftleftarrows", display: "⇇" },
      { command: "\\rightrightarrows", display: "⇉" },
      { command: "\\leftrightarrows", display: "⇆" },
      { command: "\\rightleftarrows", display: "⇄" },
      { command: "\\Lleftarrow", display: "⇚" },
      { command: "\\Rrightarrow", display: "⇛" },
      { command: "\\twoheadleftarrow", display: "↞" },
      { command: "\\twoheadrightarrow", display: "↠" },
      { command: "\\leftarrowtail", display: "↢" },
      { command: "\\rightarrowtail", display: "↣" },
      { command: "\\looparrowleft", display: "↫" },
      { command: "\\looparrowright", display: "↬" },
      { command: "\\curvearrowleft", display: "↶" },
      { command: "\\curvearrowright", display: "↷" },
      { command: "\\circlearrowleft", display: "↺" },
      { command: "\\circlearrowright", display: "↻" },
      { command: "\\upuparrows", display: "⇈" },
      { command: "\\downdownarrows", display: "⇊" },
      { command: "\\upharpoonleft", display: "↿" },
      { command: "\\upharpoonright", display: "↾" },
      { command: "\\downharpoonleft", display: "⇃" },
      { command: "\\downharpoonright", display: "⇂" },
      { command: "\\rightsquigarrow", display: "⇝" },
      { command: "\\leftrightsquigarrow", display: "↭" },
      { command: "\\multimap", display: "⊸" },
      { command: "\\dashrightarrow", display: "⇢" },
      { command: "\\dashleftarrow", display: "⇠" },
    ],
  },
  {
    label: "Delimiters",
    symbols: [
      { command: "\\lfloor", display: "⌊" },
      { command: "\\rfloor", display: "⌋" },
      { command: "\\lceil", display: "⌈" },
      { command: "\\rceil", display: "⌉" },
      { command: "\\langle", display: "⟨" },
      { command: "\\rangle", display: "⟩" },
      { command: "\\lvert", display: "|" },
      { command: "\\rvert", display: "|" },
      { command: "\\lVert", display: "∥" },
      { command: "\\rVert", display: "∥" },
      { command: "\\ulcorner", display: "⌜" },
      { command: "\\urcorner", display: "⌝" },
      { command: "\\llcorner", display: "⌞" },
      { command: "\\lrcorner", display: "⌟" },
      { command: "\\lmoustache", display: "⎰" },
      { command: "\\rmoustache", display: "⎱" },
      { command: "\\lgroup", display: "⟮" },
      { command: "\\rgroup", display: "⟯" },
      { command: "\\{", display: "{" },
      { command: "\\}", display: "}" },
      { command: "\\lbrack", display: "[" },
      { command: "\\rbrack", display: "]" },
      { command: "\\left(...\\right)", display: "(…)" },
      { command: "\\left[...\\right]", display: "[…]" },
      { command: "\\left\\{...\\right\\}", display: "{…}" },
      { command: "\\left\\langle...\\right\\rangle", display: "⟨…⟩" },
      { command: "\\left\\lvert...\\right\\rvert", display: "|…|" },
      { command: "\\left\\lVert...\\right\\rVert", display: "∥…∥" },
    ],
  },
  {
    label: "Big Operators",
    symbols: [
      { command: "\\sum", display: "∑" },
      { command: "\\prod", display: "∏" },
      { command: "\\coprod", display: "∐" },
      { command: "\\int", display: "∫" },
      { command: "\\iint", display: "∬" },
      { command: "\\iiint", display: "∭" },
      { command: "\\oint", display: "∮" },
      { command: "\\bigcap", display: "⋂" },
      { command: "\\bigcup", display: "⋃" },
      { command: "\\bigsqcup", display: "⨆" },
      { command: "\\bigvee", display: "⋁" },
      { command: "\\bigwedge", display: "⋀" },
      { command: "\\bigoplus", display: "⨁" },
      { command: "\\bigotimes", display: "⨂" },
      { command: "\\bigodot", display: "⨀" },
      { command: "\\biguplus", display: "⨄" },
      { command: "\\lim", display: "lim" },
      { command: "\\max", display: "max" },
      { command: "\\min", display: "min" },
      { command: "\\sup", display: "sup" },
      { command: "\\inf", display: "inf" },
      { command: "\\liminf", display: "lim inf" },
      { command: "\\limsup", display: "lim sup" },
      { command: "\\det", display: "det" },
      { command: "\\gcd", display: "gcd" },
      { command: "\\Pr", display: "Pr" },
    ],
  },
  {
    label: "Math Misc",
    symbols: [
      { command: "\\infty", display: "∞" },
      { command: "\\partial", display: "∂" },
      { command: "\\nabla", display: "∇" },
      { command: "\\triangle", display: "△" },
      { command: "\\square", display: "□" },
      { command: "\\lozenge", display: "◊" },
      { command: "\\angle", display: "∠" },
      { command: "\\measuredangle", display: "∡" },
      { command: "\\sphericalangle", display: "∢" },
      { command: "\\forall", display: "∀" },
      { command: "\\exists", display: "∃" },
      { command: "\\nexists", display: "∄" },
      { command: "\\emptyset", display: "∅" },
      { command: "\\varnothing", display: "∅" },
      { command: "\\neg", display: "¬" },
      { command: "\\top", display: "⊤" },
      { command: "\\bot", display: "⊥" },
      { command: "\\ell", display: "ℓ" },
      { command: "\\hbar", display: "ℏ" },
      { command: "\\hslash", display: "ℏ" },
      { command: "\\aleph", display: "ℵ" },
      { command: "\\beth", display: "ℶ" },
      { command: "\\gimel", display: "ℷ" },
      { command: "\\daleth", display: "ℸ" },
      { command: "\\wp", display: "℘" },
      { command: "\\Re", display: "ℜ" },
      { command: "\\Im", display: "ℑ" },
      { command: "\\prime", display: "′" },
      { command: "\\backslash", display: "\\" },
      { command: "\\surd", display: "√" },
      { command: "\\square", display: "□" },
      { command: "\\blacksquare", display: "■" },
      { command: "\\blacktriangle", display: "▲" },
      { command: "\\blacktriangledown", display: "▼" },
      { command: "\\blacktriangleleft", display: "◀" },
      { command: "\\blacktriangleright", display: "▶" },
      { command: "\\bigstar", display: "★" },
      { command: "\\clubsuit", display: "♣" },
      { command: "\\diamondsuit", display: "♢" },
      { command: "\\heartsuit", display: "♡" },
      { command: "\\spadesuit", display: "♠" },
      { command: "\\mho", display: "℧" },
      { command: "\\Finv", display: "Ⅎ" },
      { command: "\\Game", display: "⅁" },
      { command: "\\Bbbk", display: "𝕜" },
      { command: "\\complement", display: "∁" },
      { command: "\\circledS", display: "Ⓢ" },
      { command: "\\yen", display: "¥" },
      { command: "\\checkmark", display: "✓" },
      { command: "\\maltese", display: "✠" },
      { command: "\\diagup", display: "╱" },
      { command: "\\diagdown", display: "╲" },
    ],
  },
  {
    label: "Dots",
    symbols: [
      { command: "\\dots", display: "…" },
      { command: "\\ldots", display: "…" },
      { command: "\\cdots", display: "⋯" },
      { command: "\\vdots", display: "⋮" },
      { command: "\\ddots", display: "⋱" },
      { command: "\\therefore", display: "∴" },
      { command: "\\because", display: "∵" },
    ],
  },
  {
    label: "Math Alphabets",
    symbols: [
      { command: "\\mathbb{N}", display: "ℕ" },
      { command: "\\mathbb{Z}", display: "ℤ" },
      { command: "\\mathbb{Q}", display: "ℚ" },
      { command: "\\mathbb{R}", display: "ℝ" },
      { command: "\\mathbb{C}", display: "ℂ" },
      { command: "\\mathbb{P}", display: "ℙ" },
      { command: "\\mathbb{A}", display: "𝔸" },
      { command: "\\mathbb{H}", display: "ℍ" },
      { command: "\\mathbb{1}", display: "𝟙" },
      { command: "\\mathcal{A}", display: "𝒜" },
      { command: "\\mathcal{B}", display: "ℬ" },
      { command: "\\mathcal{C}", display: "𝒞" },
      { command: "\\mathcal{D}", display: "𝒟" },
      { command: "\\mathcal{E}", display: "ℰ" },
      { command: "\\mathcal{F}", display: "ℱ" },
      { command: "\\mathcal{G}", display: "𝒢" },
      { command: "\\mathcal{H}", display: "ℋ" },
      { command: "\\mathcal{I}", display: "ℐ" },
      { command: "\\mathcal{J}", display: "𝒥" },
      { command: "\\mathcal{K}", display: "𝒦" },
      { command: "\\mathcal{L}", display: "ℒ" },
      { command: "\\mathcal{M}", display: "ℳ" },
      { command: "\\mathcal{N}", display: "𝒩" },
      { command: "\\mathcal{O}", display: "𝒪" },
      { command: "\\mathcal{P}", display: "𝒫" },
      { command: "\\mathcal{Q}", display: "𝒬" },
      { command: "\\mathcal{R}", display: "ℛ" },
      { command: "\\mathcal{S}", display: "𝒮" },
      { command: "\\mathcal{T}", display: "𝒯" },
      { command: "\\mathcal{U}", display: "𝒰" },
      { command: "\\mathcal{V}", display: "𝒱" },
      { command: "\\mathcal{W}", display: "𝒲" },
      { command: "\\mathcal{X}", display: "𝒳" },
      { command: "\\mathcal{Y}", display: "𝒴" },
      { command: "\\mathcal{Z}", display: "𝒵" },
      { command: "\\mathfrak{A}", display: "𝔄" },
      { command: "\\mathfrak{B}", display: "𝔅" },
      { command: "\\mathfrak{C}", display: "ℭ" },
      { command: "\\mathfrak{a}", display: "𝔞" },
      { command: "\\mathfrak{b}", display: "𝔟" },
      { command: "\\mathfrak{g}", display: "𝔤" },
      { command: "\\mathscr{A}", display: "𝒜" },
      { command: "\\mathscr{B}", display: "ℬ" },
      { command: "\\mathbf{ }", display: "𝐁" },
      { command: "\\mathit{ }", display: "𝐼" },
      { command: "\\mathrm{ }", display: "R" },
      { command: "\\mathsf{ }", display: "𝖲" },
      { command: "\\mathtt{ }", display: "𝚃" },
      { command: "\\mathfrak{ }", display: "𝔉" },
    ],
  },
  {
    label: "Accents",
    symbols: [
      { command: "\\hat{x}", display: "x̂" },
      { command: "\\widehat{xyz}", display: "x̂yz" },
      { command: "\\tilde{x}", display: "x̃" },
      { command: "\\widetilde{xyz}", display: "x̃yz" },
      { command: "\\bar{x}", display: "x̄" },
      { command: "\\overline{xyz}", display: "x̄yz" },
      { command: "\\underline{xyz}", display: "xyz" },
      { command: "\\vec{x}", display: "x⃗" },
      { command: "\\overrightarrow{AB}", display: "A⃗B" },
      { command: "\\overleftarrow{AB}", display: "A⃖B" },
      { command: "\\dot{x}", display: "ẋ" },
      { command: "\\ddot{x}", display: "ẍ" },
      { command: "\\dddot{x}", display: "x⃛" },
      { command: "\\ddddot{x}", display: "x⃜" },
      { command: "\\check{x}", display: "x̌" },
      { command: "\\breve{x}", display: "x̆" },
      { command: "\\acute{x}", display: "x́" },
      { command: "\\grave{x}", display: "x̀" },
      { command: "\\mathring{x}", display: "x̊" },
      { command: "\\overbrace{xyz}", display: "x⏞yz" },
      { command: "\\underbrace{xyz}", display: "x⏟yz" },
      { command: "\\overset{a}{=}", display: "a=" },
      { command: "\\underset{a}{=}", display: "a=" },
      { command: "\\stackrel{a}{=}", display: "a=" },
      { command: "\\xrightarrow{text}", display: "→" },
      { command: "\\xleftarrow{text}", display: "←" },
      { command: "\\xmapsto{text}", display: "↦" },
      { command: "\\xleftrightarrow{text}", display: "↔" },
      { command: "\\xhookrightarrow{text}", display: "↪" },
      { command: "\\xhookleftarrow{text}", display: "↩" },
      { command: "\\xleftharpoondown{text}", display: "↽" },
      { command: "\\xrightharpoondown{text}", display: "⇁" },
      { command: "\\xleftharpoonup{text}", display: "↼" },
      { command: "\\xrightharpoonup{text}", display: "⇀" },
      { command: "\\xleftrightharpoons{text}", display: "⇋" },
      { command: "\\xrightleftharpoons{text}", display: "⇌" },
    ],
  },
  {
    label: "Text Symbols",
    symbols: [
      { command: "\\textsterling",      renderAs: "\\text{£}",         display: "£" },
      { command: "\\texteuro",          renderAs: "\\text{€}",         display: "€" },
      { command: "\\textyen",           renderAs: "\\text{¥}",         display: "¥" },
      { command: "\\textdegree",        renderAs: "\\text{°}",         display: "°" },
      { command: "\\textcelsius",       renderAs: "\\text{℃}",        display: "℃" },
      { command: "\\textdagger",        renderAs: "\\text{†}",         display: "†" },
      { command: "\\textdaggerdbl",     renderAs: "\\text{‡}",         display: "‡" },
      { command: "\\textsection",       renderAs: "\\text{§}",         display: "§" },
      { command: "\\textparagraph",     renderAs: "\\text{¶}",         display: "¶" },
      { command: "\\textregistered",    renderAs: "\\text{®}",         display: "®" },
      { command: "\\texttrademark",     renderAs: "\\text{™}",         display: "™" },
      { command: "\\textcopyright",     renderAs: "\\text{©}",         display: "©" },
      { command: "\\textbullet",        renderAs: "\\bullet",          display: "•" },
      { command: "\\textperiodcentered",renderAs: "\\cdot",            display: "·" },
      { command: "\\textellipsis",       renderAs: "\\dots",           display: "…" },
      { command: "\\textemdash",        renderAs: "\\text{—}",         display: "—" },
      { command: "\\textendash",        renderAs: "\\text{–}",         display: "–" },
      { command: "\\textquotedblleft",  renderAs: "\\text{“}",         display: "“" },
      { command: "\\textquotedblright", renderAs: "\\text{”}",         display: "”" },
      { command: "\\textquoteleft",     renderAs: "\\text{‘}",         display: "‘" },
      { command: "\\textquoteright",    renderAs: "\\text{’}",         display: "’" },
      { command: "\\#",                 display: "#" },
      { command: "\\&",                 display: "&" },
      { command: "\\%",                 display: "%" },
      { command: "\\$",                 display: "$" },
      { command: "\\_",                 display: "_" },
      { command: "\\{",                 display: "{" },
      { command: "\\}",                 display: "}" },
      { command: "\\P",                 display: "¶" },
      { command: "\\S",                 display: "§" },
      { command: "\\pounds",            renderAs: "\\text{£}",         display: "£" },
    ],
  },
];
