/**
 * Interaction — when to create persisted figure/plot objects for chat.
 *
 * Spec/kind validation and path checks live in main; args/examples on interaction-* tools.
 * Chat one-shot file peeks use ```artifact fences — not this module.
 */
import { TOOL_NAMES } from "../../../../shared/agent/tool-names";

export const INTERACTION_PROMPT = [
  "## Interaction (figures & plots)",
  "",
  "Persisted, **revisitable** figure and plot objects under `.workbench/interactions/<id>/`.",
  "After a successful write, embed the tool-returned `fenceMarkdown` (`interaction` fence with `id`)",
  " in the assistant reply so the user gets a **clickable card** and can reopen the same view later.",
  "",
  "### Scope boundary",
  "",
  "- **This module** — when to create/update Interaction specs vs one-shot chat previews;",
  "  route among interaction-* tools; not spec field manuals.",
  "- **`artifact` fence** — one-shot peek at an on-disk file path in chat (`path:` / optional `title:`);",
  "  no revisit, no `.workbench/interactions/`.",
  "- **Experiments** — run outputs and `results-snapshot`; when a figure or metrics CSV deserves a",
  "  durable view, promote to Interaction here — otherwise a peek or prose may suffice.",
  "- **Manuscript compile** — compiled PDF preview in chat; do not wrap or convert just to glance once.",
  "- **Run `artifacts[]`** — paths recorded on experiment runs; not Interaction specs themselves.",
  "- **Not** a live interactive sandbox; advanced interactive engines are out of scope for this module.",
  "",
  "### One-shot file peek",
  "",
  "- Quick glance at an on-disk file in chat → `artifact` fence with `path:` (and optional `title:`).",
  "  Not an Interaction card — no revisit, no `.workbench/interactions/`.",
  "",
  "### When this applies",
  "",
  "- A figure or plot should be **revisited**, compared, or referenced across later turns.",
  "- After analysis or an experiment produces a PNG/PDF/SVG or metrics CSV worth a durable view.",
  "- User asks what Interaction objects exist or to re-embed/update an existing card.",
  "",
  "### When not to use Interaction",
  "",
  "- A **one-time** path peek → `artifact` fence only.",
  "- The backing file **does not exist yet** — produce it first (Experiments, compile, edit), then write.",
  "- Only need the model to **see pixels once** → `read` (vision-capable) or `image-describe` — no spec required.",
  "",
  "### Route the request",
  "",
  "Guidance in order; skip what the request does not need:",
  "",
  "1. **One-shot path peek?** → `artifact` fence with `path:`. Stop.",
  "2. **Reopenable figure or CSV plot?** — source file must **already exist** on disk, then",
  `   \`${TOOL_NAMES.interactionWrite}\` (how-to on that tool). Embed returned \`fenceMarkdown\` in the reply.`,
  `3. **Update or re-embed?** → \`${TOOL_NAMES.interactionList}\` / \`${TOOL_NAMES.interactionRead}\`,`,
  "   then write when the spec or title should change.",
  `4. **User asks to open the panel now?** → \`${TOOL_NAMES.interactionOpen}\`. Otherwise the chat card is usually enough.`,
  "",
  "### Kind judgment (summary)",
  "",
  "- **`figure.static`** — a finished file on disk (PDF, PNG, SVG, …).",
  "- **`plot.*`** — CSV-backed charts; use real columns from an on-disk CSV in `resources[]` —",
  "  do not invent series or columns. Valid kinds and `params` mapping are validated by the write tool / spec.",
  "- When unsure of kind or columns, read the CSV and follow `interaction-write` — do not guess.",
  "",
  "### Judgment",
  "",
  "- Prefer Interaction when the view may return; prefer `artifact` for a quick peek.",
  "- After **Experiments** surfaces figures/tables, create Interaction only when revisit/compare matters.",
  "- A compiled PDF already has chat preview — do not bash-convert just to look once.",
  "- Need pixels and the chat model cannot view images →",
  `  \`${TOOL_NAMES.imageDescribe}\`. When vision is available, \`read\` PNG/JPG instead.`,
  "- After `interaction-write` succeeds, embed `fenceMarkdown` — the card is part of the deliverable.",
  "- Tool how-to stays on the tools; project rules may tighten naming — defer to them.",
].join("\n");
