import { TOOL_NAMES } from "../../../shared/tool-names";

/**
 * Citation audit — when to call citation-health; how-to lives on that tool.
 */
export const CITATION_AUDIT_PROMPT = [
  "## Citation & bibliography audit",
  "",
  "Manuscript citation **compliance**: every `\\cite{key}` in project `.tex` ↔ project `.bib` ↔",
  "`.prismnext/library/` in one grounded snapshot. This is not library browsing and not chat `[n]` staging.",
  "",
  "### Scope boundary",
  "",
  "- **This module** — user wants to know whether the manuscript bibliography is complete, consistent,",
  "  and traceable (missing keys, unused keys, library gaps, suspected fabrication).",
  "- **Literature library** — find/read/cite library papers in discussion (`[@bibkey]`).",
  "- **Chat paper citations** — external `[n]` refs in chat; they do not replace manuscript `\\cite{}` checks.",
  "",
  "### When this applies",
  "",
  "- User asks to check citations, bibliography, missing keys, unused keys, or reference integrity.",
  "- You are about to write a compliance or peer-review-style report on the manuscript's references.",
  "- After large `.tex` or `.bib` edits when the user expects a fresh integrity picture.",
  "",
  "### Route the request",
  "",
  "Ask in order:",
  "",
  "1. **Is this a manuscript audit or a chat reading list?** Manuscript → this module. External reading → Chat paper citations.",
  "2. **Do you already have a snapshot?** If **Session citation audit (this chat)** appears in this chat's context,",
  "   reuse it unless `.tex`/`.bib` changed or the user asked for a fresh check.",
  "3. **Run the audit in this conversation** — call `" +
    TOOL_NAMES.citationHealth +
    "` directly; binding rules (no Task/subagent, no read/glob substitutes) live on that tool.",
  "4. **Report only after the tool returns** — ground claims in its JSON; do not guess missing keys.",
  "",
  "### After audit",
  "",
  `- Recommend explicit .bib syncs with \`${TOOL_NAMES.literatureExportBib}\` when keys should come from the library.`,
  "- Flag `verified: false` / untraceable entries as suspected fabrication — do not recommend importing them without user confirmation.",
  "- Optional prose review of how citations read in the manuscript — orchestrator: delegate to",
  "  `peer-reviewer` with the audit snapshot (instruct it not to re-scan files); experts cannot Task,",
  "  so note prose issues in your own report instead.",
  "",
  "### Judgment",
  "",
  "- One audit call covers the full `.tex` ↔ `.bib` ↔ library picture — do not stitch partial scans.",
  "- Library-only questions (\"what papers do we have on X?\") → Literature library, not this module.",
  "- If the user only wants to add one external paper to chat, use Chat paper citations — not a full manuscript audit.",
  "- Project rules may define bib paths or export policy — defer to them when proposing fixes.",
].join("\n");
