/** Citation & bibliography management rules for Prism. */
export const CITATIONS_PROMPT = [
  "## Citations & Bibliography",
  "",
  "- Use \\cite{key} for parenthetical citations and \\textcite{key} for in-text citations.",
  "- Manage references with BibTeX (.bib files); use \\bibliography{filename} to include them.",
  "- The bib tool is auto-detected: biblatex uses biber, traditional LaTeX uses bibtex.",
  "- For biblatex users, prefer \\addbibresource{refs.bib} over \\bibliography{}.",
  "- When adding a new reference, use Google Scholar's BibTeX export or doi2bib.org.",
  "- Always check that every \\cite key has a matching entry in the .bib file.",
  "- Common biblatex commands: \\textcite (author in text), \\parencite (parenthetical),",
  "  \\footcite (footnote), \\autocite (context-sensitive).",
  "",
  "## Project Literature Library (Prism tools)",
  "",
  "The project keeps a SQLite library at `.prismnext/library/library.db` (NOT .bib files).",
  "When the user asks about papers already in Literature mode, prefer these tools:",
  "",
  "- **`literature-read`** — lookup by exact **bibkey** (Cite key in Literature panel).",
  "  Returns metadata, abstract, publication_details, highlights, PDF path.",
  "  Do NOT substitute `task`, `websearch`, or `read` on library.db.",
  "- **`literature-search`** — full-text search **only within the local library** (`library.db`).",
  "  Use it to find papers already added to the project. It does NOT search the web.",
  "- **`literature-stage`** — verify a known DOI/arXiv via external catalogs (Crossref/arXiv/OpenAlex/…)",
  "  and stage a session citation. Returns metadata + a `refId`. **No library write.**",
  "  This is the DEFAULT for any paper you cite — do not call literature-add unless the user",
  "  explicitly asks to add the paper to the library.",
  "  Catalog lookup must succeed; invalid DOIs are rejected. **Never invent DOIs** —",
  "  copy exact identifiers from websearch or the user message.",
  "",
  "  ### How to cite papers in your reply (IMPORTANT)",
  "  - For EVERY paper you mention, call `literature-stage` first with its exact DOI or arXiv ID,",
  "    then reference the returned `refId` as **`[n]`** in your text — e.g. \"World models [1] enable…\".",
  "  - **Always use `[n]` markers** (square brackets around the number). Do NOT use markdown",
  "    ordered lists (`1.` `2.` …) or bare numbers (`#1`, `paper 1`) to refer to staged citations —",
  "    only `[n]` becomes a clickable citation that opens the paper's metadata panel.",
  "  - **Citation layout:** one paper per line — `**Title** [n]` then a short summary on the",
  "    next line. Never mix list numbers with citation refs (bad: `4. [3]`; good: `**Title** [3]`).",
  "    Never write the literal `[n]` placeholder — always substitute the actual refId number.",
  "  - `[n]` works inside tables, lists, and paragraphs. Reuse the same `[n]` if you mention the",
  "    same paper again in the same reply.",
  "  - If `literature-stage` returns `verified: false`, do NOT write `[n]` for it; tell the user the",
  "    identifier could not be verified and ask for the correct one.",
  "",
  "  ### Finding papers by topic (e.g. \"recent world model papers\")",
  "  - The catalog tools do **not** do topic+date search. Use `websearch` to discover papers,",
  "    extract each result's **arXiv ID or DOI**, then `literature-stage` each one to verify + stage.",
  "  - Do not list a paper with `[n]` unless `literature-stage` succeeded for it.",
  "  - Workflow: websearch → collect exact arXiv IDs/DOIs → literature-stage (one per paper) →",
  "    cite as `[n]` in the reply → (only if user asks) literature-add to write into the library.",
  "- **`literature-add`** — write a verified paper into the project library. Use ONLY when",
  "  the user explicitly says \"add to library\" / \"加入文献库\". Never auto-invoke.",
  "- **`literature-cite`** — append a library paper's BibTeX entry to the project `.bib`.",
  "",
  "If the user @-mentions a library paper, bibliographic metadata is already in the prompt.",
  "Use `literature-read` only for highlights/annotations or when they give an explicit bibkey.",
].join("\n");
