// prism-next/src/main/prompts/modules/index.ts

import type { PromptModule, PromptContext } from "../types";
import { CHAT_CITATION_STAGING_PROMPT } from "./chat-citation-staging";
import { CITATION_AUDIT_PROMPT } from "./citation-audit";
import { LITERATURE_LIBRARY_PROMPT } from "./literature-library";
import { RESEARCH_REASONING_PROMPT } from "../stable/research-reasoning";
import { REPLY_DEPTH_PROMPT } from "../stable/reply-depth";
import { buildOrchestratorJudgmentPrompt } from "./orchestrator-judgment";
import { PROJECT_BRIEF_PROMPT } from "./project-brief";
import { RESEARCH_DESIGN_PROMPT } from "./research-design";
import { EXPERIMENTS_PROMPT } from "./experiments";
import { INTERACTION_PROMPT } from "./interaction";
import { PROJECT_RULES_MEMORY_PROMPT } from "./project-rules-memory";
import { SUBAGENT_ROLE_PROMPT } from "./subagent-role";
import { buildManuscriptCompilePrompt } from "./manuscript-compile";
import { buildWorkspacePrompt } from "../stable/workspace-folders";

/** All available prompt modules.
 *
 * Global `_prism-system.md` injects all modules with `profileOnly: false`.
 * Shared profile modules auto-attach to orchestrator + experts; orchestratorOnly /
 * expertOnly modules attach only to that role — no per-agent UI selection.
 *
 * Per-tool how-to → `src/main/agent/tools/` descriptions only (not modules).
 * Hard/Soft homes: `docs-private/superpowers/specs/2026-07-21-prompt-hard-soft-architecture-design.md`.
 */
export const ALL_MODULES: PromptModule[] = [
  {
    key: "workspace-folders",
    label: "Workspace Folder Descriptions",
    description:
      "Auto-generated from project workspace configuration. " +
      "Tells the agent about each functional folder and its purpose.",
    enabled: true,
    source: "project",
    autoGenerated: true,
    build: (ctx: PromptContext) =>
      ctx.workspaceDirs ? buildWorkspacePrompt(ctx.workspaceDirs) : "",
  },
  {
    key: "chat-citation-staging",
    label: "Chat Paper Citations",
    description:
      "External papers in chat: literature-stage first, cite as [n]. Library papers use the Literature Library module.",
    enabled: true,
    profileOnly: true,
    source: "app",
    prompt: CHAT_CITATION_STAGING_PROMPT,
  },
  {
    key: "citation-audit",
    label: "Citation & Bibliography Audit",
    description:
      "Manuscript .tex ↔ .bib ↔ library compliance via citation-health — not read/glob scans.",
    enabled: true,
    profileOnly: true,
    source: "app",
    prompt: CITATION_AUDIT_PROMPT,
  },
  {
    key: "literature-library",
    label: "Literature Library (tags & search)",
    description:
      "Project library papers: search/read in the current project library, cite as [@bibkey]. External papers use Chat Paper Citations.",
    enabled: true,
    profileOnly: true,
    source: "app",
    prompt: LITERATURE_LIBRARY_PROMPT,
  },
  {
    key: "orchestrator-judgment",
    label: "Orchestrator Judgment",
    description:
      "Proactive scheduling + Task delegation — read the request, engage domains, delegate, synthesize.",
    enabled: true,
    profileOnly: true,
    orchestratorOnly: true,
    source: "app",
    build: buildOrchestratorJudgmentPrompt,
  },
  {
    key: "manuscript-compile",
    label: "Manuscript & paper compile",
    description:
      "Manuscript writing & build verify for LaTeX and Typst; entry from Workspace Manuscript folder pin.",
    enabled: true,
    profileOnly: true,
    source: "app",
    build: buildManuscriptCompilePrompt,
  },
  {
    key: "research-reasoning",
    label: "Scholarly Reasoning (synthesis & critique)",
    description:
      "Cross-paper synthesis, steelman/rebut, confidence calibration for research questions. Global baseline for all agents.",
    enabled: true,
    profileOnly: false,
    source: "app",
    prompt: RESEARCH_REASONING_PROMPT,
  },
  {
    key: "reply-depth",
    label: "Reply Depth & Structure",
    description:
      "Calibrate reply length/structure to request type — thorough for research, short for tool/status. Judgment-based, not quotas. Global baseline for all agents.",
    enabled: true,
    profileOnly: false,
    source: "app",
    prompt: REPLY_DEPTH_PROMPT,
  },
  {
    key: "project-brief",
    label: "Project Brief (`.brief.md`)",
    description:
      "Intellectual spine at project-root `.brief.md` — thesis line, not memory, rules, or experiment plans.",
    enabled: true,
    profileOnly: true,
    source: "app",
    prompt: PROJECT_BRIEF_PROMPT,
  },
  {
    key: "project-rules-memory",
    label: "Project Rules (remember)",
    description:
      "When to persist stable preferences into Settings project rules via project-rule-write.",
    enabled: true,
    profileOnly: true,
    source: "app",
    prompt: PROJECT_RULES_MEMORY_PROMPT,
  },
  {
    key: "research-design",
    label: "Research Design",
    description:
      "Scientific thinking and intellectual roadmap — explore, pressure-test, Plan/coach; not experiment design.",
    enabled: true,
    profileOnly: true,
    source: "app",
    prompt: RESEARCH_DESIGN_PROMPT,
  },
  {
    key: "experiments",
    label: "Experiments (log & runs)",
    description:
      "Experiment islands under the Workspace Experiment folder — create/read, run+log discipline, methodology-auditor handoff.",
    enabled: true,
    profileOnly: true,
    source: "app",
    prompt: EXPERIMENTS_PROMPT,
  },
  {
    key: "interaction",
    label: "Interaction (figures & plots)",
    description:
      "Persisted figures/plots as clickable chat cards — when to use interaction-* vs ```artifact.",
    enabled: true,
    profileOnly: true,
    source: "app",
    prompt: INTERACTION_PROMPT,
  },
  {
    key: "subagent-role",
    label: "Subagent Role (experts)",
    description:
      "Expert/subagent only: follow role instructions first; focused Task deliverable; not for the primary orchestrator.",
    enabled: true,
    profileOnly: true,
    expertOnly: true,
    source: "app",
    prompt: SUBAGENT_ROLE_PROMPT,
  },
];
