// prism-next/src/main/prompts/modules/index.ts

import type { PromptModule, PromptContext } from "../types";
import { ACADEMIC_WRITING_PROMPT } from "./academic-writing";
import { CITATIONS_PROMPT } from "./citations";
import { CHAT_CITATION_STAGING_PROMPT } from "./chat-citation-staging";
import { LITERATURE_LIBRARY_PROMPT } from "./literature-library";
import { FIGURES_TABLES_PROMPT } from "./figures-tables";
import { MATH_EQUATIONS_PROMPT } from "./math-equations";
import { buildWorkspacePrompt } from "./workspace-folders";

/** All available prompt modules.
 *
 *  Academic modules are enabled by default so built-in agent profiles work
 *  out of the box. Users can turn them off in Settings → Prompts & Rules;
 *  profiles that depend on disabled modules become unavailable until re-enabled.
 *
 *  `workspace-folders` generates folder descriptions from the project workspace config.
 */
export const ALL_MODULES: PromptModule[] = [
  {
    key: "workspace-folders",
    label: "Workspace Folder Descriptions",
    description:
      "Auto-generated from project workspace configuration. " +
      "Tells the agent about each functional folder and its purpose.",
    enabled: true,
    source: "project",
    autoGenerated: true,
    build: (ctx: PromptContext) =>
      ctx.workspaceDirs ? buildWorkspacePrompt(ctx.workspaceDirs) : "",
  },
  {
    key: "academic-writing",
    label: "Academic Writing",
    description: "Sectioning, abstracts, cross-references, footnotes, hyperref.",
    enabled: true,
    source: "app",
    prompt: ACADEMIC_WRITING_PROMPT,
  },
  {
    key: "citations",
    label: "Citations & Bibliography",
    description: "BibTeX, BibLaTeX, cite commands, bibliography management.",
    enabled: true,
    source: "app",
    prompt: CITATIONS_PROMPT,
  },
  {
    key: "chat-citation-staging",
    label: "Chat Paper Citations",
    description:
      "Binding workflow for external papers in chat: literature-stage first, cite as [n]. Not a tool catalog.",
    enabled: true,
    source: "app",
    prompt: CHAT_CITATION_STAGING_PROMPT,
  },
  {
    key: "literature-library",
    label: "Literature Library (tags & search)",
    description:
      "How to find project library papers by user tags, AI summaries, literature-search, and literature-read.",
    enabled: true,
    source: "app",
    prompt: LITERATURE_LIBRARY_PROMPT,
  },
  {
    key: "figures-tables",
    label: "Figures & Tables",
    description: "Floats, captions, booktabs, subcaption, graphicx.",
    enabled: true,
    source: "app",
    prompt: FIGURES_TABLES_PROMPT,
  },
  {
    key: "math-equations",
    label: "Math & Equations",
    description: "AMS packages, align, matrices, theorem environments.",
    enabled: true,
    source: "app",
    prompt: MATH_EQUATIONS_PROMPT,
  },
];
