/**
 * Capability-module catalog facade.
 *
 * Each subdirectory is one building block. Import this file (or the package
 * root `src/main/prompts`) — never `modules/<key>/prompt.ts` or `build.ts`.
 *
 * Global (`profileOnly: false`) entries live in `stable/` and are registered
 * here so the catalog stays one list. Host identity is not a module.
 */
import type { PromptContext, PromptModule } from "../types";
import { RESEARCH_REASONING_PROMPT } from "../stable/research-reasoning";
import { REPLY_DEPTH_PROMPT } from "../stable/reply-depth";
import { buildWorkspacePrompt } from "../stable/workspace-folders";
import { CHAT_CITATION_STAGING_MODULE } from "./chat-citation-staging";
import { CITATION_AUDIT_MODULE } from "./citation-audit";
import { LITERATURE_LIBRARY_MODULE } from "./literature-library";
import { WEB_RESEARCH_MODULE } from "./web-research";
import { OFFICE_DOCUMENTS_MODULE } from "./office-documents";
import { ORCHESTRATOR_JUDGMENT_MODULE } from "./orchestrator-judgment";
import { MANUSCRIPT_COMPILE_MODULE } from "./manuscript-compile";
import { PROJECT_BRIEF_MODULE } from "./project-brief";
import { PROJECT_RULES_MEMORY_MODULE } from "./project-rules-memory";
import { RESEARCH_DESIGN_MODULE } from "./research-design";
import { EXPERIMENTS_MODULE } from "./experiments";
import { INTERACTION_MODULE } from "./interaction";
import { SUBAGENT_ROLE_MODULE } from "./subagent-role";

export { CHAT_CITATION_STAGING_PROMPT, CHAT_CITATION_STAGING_MODULE } from "./chat-citation-staging";
export { CITATION_AUDIT_PROMPT, CITATION_AUDIT_MODULE } from "./citation-audit";
export { LITERATURE_LIBRARY_PROMPT, LITERATURE_LIBRARY_MODULE } from "./literature-library";
export { WEB_RESEARCH_PROMPT, WEB_RESEARCH_MODULE } from "./web-research";
export { OFFICE_DOCUMENTS_PROMPT, OFFICE_DOCUMENTS_MODULE } from "./office-documents";
export {
  ORCHESTRATOR_JUDGMENT_PROMPT,
  buildOrchestratorJudgmentPrompt,
  ORCHESTRATOR_JUDGMENT_MODULE,
} from "./orchestrator-judgment";
export { buildManuscriptCompilePrompt, MANUSCRIPT_COMPILE_MODULE } from "./manuscript-compile";
export { PROJECT_BRIEF_PROMPT, PROJECT_BRIEF_MODULE } from "./project-brief";
export { PROJECT_RULES_MEMORY_PROMPT, PROJECT_RULES_MEMORY_MODULE } from "./project-rules-memory";
export { RESEARCH_DESIGN_PROMPT, RESEARCH_DESIGN_MODULE } from "./research-design";
export { EXPERIMENTS_PROMPT, EXPERIMENTS_MODULE } from "./experiments";
export { INTERACTION_PROMPT, INTERACTION_MODULE } from "./interaction";
export { SUBAGENT_ROLE_PROMPT, SUBAGENT_ROLE_MODULE } from "./subagent-role";

const WORKSPACE_FOLDERS_MODULE: PromptModule = {
  key: "workspace-folders",
  label: "Workspace Folder Descriptions",
  description:
    "Auto-generated from project workspace configuration. " +
    "Tells the agent about each functional folder and its purpose.",
  enabled: true,
  source: "project",
  autoGenerated: true,
  build: (ctx: PromptContext) =>
    ctx.workspaceDirs ? buildWorkspacePrompt(ctx.workspaceDirs) : "",
};

const RESEARCH_REASONING_MODULE: PromptModule = {
  key: "research-reasoning",
  label: "Scholarly Reasoning (synthesis & critique)",
  description:
    "Cross-paper synthesis, steelman/rebut, confidence calibration for research questions. Global baseline for all agents.",
  enabled: true,
  profileOnly: false,
  source: "app",
  prompt: RESEARCH_REASONING_PROMPT,
};

const REPLY_DEPTH_MODULE: PromptModule = {
  key: "reply-depth",
  label: "Reply Depth & Structure",
  description:
    "Calibrate reply length/structure to request type — thorough for research, short for tool/status. Judgment-based, not quotas. Global baseline for all agents.",
  enabled: true,
  profileOnly: false,
  source: "app",
  prompt: REPLY_DEPTH_PROMPT,
};

/** All available prompt modules.
 *
 * Global `_prism-system.md` injects all modules with `profileOnly: false`.
 * Shared profile modules auto-attach to orchestrator + experts; orchestratorOnly /
 * expertOnly modules attach only to that role — no per-agent UI selection.
 *
 * Per-tool how-to → `src/main/agent/tools/` descriptions only (not modules).
 * Hard/Soft homes: `docs-private/superpowers/specs/2026-07-21-prompt-hard-soft-architecture-design.md`.
 */
export const ALL_MODULES: PromptModule[] = [
  WORKSPACE_FOLDERS_MODULE,
  CHAT_CITATION_STAGING_MODULE,
  CITATION_AUDIT_MODULE,
  LITERATURE_LIBRARY_MODULE,
  WEB_RESEARCH_MODULE,
  OFFICE_DOCUMENTS_MODULE,
  ORCHESTRATOR_JUDGMENT_MODULE,
  MANUSCRIPT_COMPILE_MODULE,
  RESEARCH_REASONING_MODULE,
  REPLY_DEPTH_MODULE,
  PROJECT_BRIEF_MODULE,
  PROJECT_RULES_MEMORY_MODULE,
  RESEARCH_DESIGN_MODULE,
  EXPERIMENTS_MODULE,
  INTERACTION_MODULE,
  SUBAGENT_ROLE_MODULE,
];
