import { TOOL_NAMES } from "../../../shared/tool-names";

/**
 * Project library papers — when to use library tools vs external chat citations.
 * Tool parameters and gates live on literature-* tool descriptions.
 */
export const LITERATURE_LIBRARY_PROMPT = [
  "## Project literature library",
  "",
  "Papers **in** `.prismnext/library/` — the project's curated catalog with bibkeys, tags,",
  "collections, PDFs, and AI summaries. Cite these as **`[@bibkey]`** using exact keys from tool results.",
  "",
  "### Scope boundary",
  "",
  "- **This module** — papers already in the library, or the user wants to work with the library",
  "  as the source of truth (tags, collections, manuscript bibliography tied to the library).",
  "- **Chat paper citations** — papers **outside** the library cited in chat as **`[n]`**.",
  "  Do not mix formats: library papers → `[@bibkey]`; external session papers → `[n]`.",
  "- **Citation & bibliography audit** — manuscript `.tex` ↔ `.bib` ↔ library compliance.",
  "  Use that module when the user asks to *check* citations, not when browsing papers.",
  "",
  "### When this applies",
  "",
  "- User @-mentions a library paper, asks about tags/collections, or cites work already in the project.",
  "- User wants metadata, abstract, highlights, or PDF path for a **known library bibkey**.",
  "- User asks to sync manuscript `.bib` from the library or discuss bibliography **as library-backed**.",
  "- A Task returns **Library papers (this Task)** — those hits are library-grounded; cite with `[@bibkey]`.",
  "",
  "### Route the request",
  "",
  "Ask in order:",
  "",
  "1. **Is the paper already in the library?**",
  "   - Yes → library path below. Never stage as `[n]` for a bibkey you can cite as `[@bibkey]`.",
  "   - No / unsure → search the library first. If still missing and the user wants *external*",
  "     recommendations, switch to **Chat paper citations** (not this module).",
  "2. **Library lookup vs external topic search?**",
  `   - Known bibkey, title in library, tags, collections → \`${TOOL_NAMES.literatureSearch}\`.`,
  `   - Topic / venue / \"papers on X\" not yet in library → \`${TOOL_NAMES.literatureDiscover}\` (external);`,
  "     that path belongs to Chat paper citations for citing in reply.",
  "3. **Metadata vs PDF body?**",
  `   - Metadata, abstract, highlights → \`${TOOL_NAMES.literatureRead}\` (and search when bibkey unknown).`,
  `   - PDF text needed → \`${TOOL_NAMES.literatureIntensiveReading}\` then \`${TOOL_NAMES.literatureReadPdf}\``,
  "     (see those tools — intensive list is per chat session).",
  "4. **Discuss vs add vs export?**",
  "   - Discussing or citing → read/search only; cite `[@bibkey]`.",
  "   - User explicitly asks to add/remove from library → add/delete tools (never auto-add while citing).",
  `   - Manuscript needs missing BibTeX entries → \`${TOOL_NAMES.literatureExportBib}\` after you know which keys matter.`,
  "",
  "### Soft workflow",
  "",
  `- Find: \`${TOOL_NAMES.literatureSearch}\` (library) — prefer tag-aware queries when the user organized by topic.`,
  `- Ground: \`${TOOL_NAMES.literatureRead}\` for the bibkeys you will rely on.`,
  "- Cite inline as **`[@bibkey]`** — reuse the same key for the same paper; never invent keys.",
  `- Manuscript sync: \`${TOOL_NAMES.literatureExportBib}\` when recommending explicit .bib updates.`,
  `- Integrity checks on the manuscript → **Citation & bibliography audit** module (\`${TOOL_NAMES.citationHealth}\`).`,
  "",
  "### Task handoff",
  "",
  "- Library Tasks accumulate search/read hits on the parent session.",
  "- Read **Library papers (this Task)** in the result before re-searching the same question.",
  "- End Task synthesis citing **`[@bibkey]`** for every library paper you relied on.",
  "- Do not re-run library search for papers already listed in the Task result unless the user asks for more.",
  "",
  "### Judgment",
  "",
  "- @-mention in the user message often already includes metadata — use read for highlights/annotations only.",
  "- Entries may include user tags and AI summaries — weight tags when the user grouped by topic.",
  "- Collections are managed in the Literature panel; filter via search when the user names a collection.",
  "- If the user only wants a reading list of *new* external papers, leave the library and use Chat paper citations.",
  "- When the project's **through-line** (`.brief.md`) is relevant, prefer papers that serve that story — not catalog filling.",
  "- Project rules may specify export paths or citation style — defer to them.",
].join("\n");
