import { TOOL_NAMES } from "../../../shared/agent/tool-names";

/**
 * Project brief — `.brief.md` intellectual spine on disk.
 * Live thinking → research-design; empirical runs → experiments.
 */
export const PROJECT_BRIEF_PROMPT = [
  "## Project brief (`.brief.md`)",
  "",
  "The project's **intellectual spine on disk** — a living summary of core ideas, claims, methodology",
  "thinking, and why this work matters. It **captures** what has settled from **Research design**",
  "dialogue; literature, experiments, and writing **align with** it as the through-line evolves.",
  "",
  "### Scope boundary",
  "",
  "- **This module** — what `.brief.md` **is**, when to read/update it, and voice on disk.",
  "- **Research design** — **live** research thinking (methods, claims, evidence paths) before or",
  "  between brief updates — not stored here until the user confirms capture.",
  "- **Experiments** — protocols, runs, ablations, metrics — not the brief file itself.",
  "- **Not** chat memory, AGENTS.md, project rules, or agent modules.",
  "",
  "### What this is",
  "",
  "- A **living thesis** at the project root: the main story you are building and revising.",
  "- May be narrative, bullets, or mixed structure — **no required outline**.",
  "- Template sections (Research question, Hypotheses, …) are a **starting scaffold only**;",
  "  users may rename, delete, or ignore them.",
  "",
  "### Voice",
  "",
  "- Write as the **researcher's own voice** — **first person** (I / we), not third-person about",
  "  \"the project\" or \"the user.\"",
  "- Example: \"I want to test whether…\" / \"We assume…\" — not \"This project aims to…\".",
  `- When updating via \`${TOOL_NAMES.researchBriefUpdate}\`, match the user's existing voice if different.`,
  "",
  "### What this is not",
  "",
  "- **Not a scratchpad** — drafts and decision records live in **`specs/`** (plain folder);",
  "  the brief holds only what has **settled**.",
  "- **Not an experiment plan** — runs and protocols → **Experiments**.",
  "- **Not a frozen gate** — it evolves; empty or partial sections are OK early on.",
  "",
  "### When to read or update",
  "",
  "- **Driven by dialogue** — not a milestone checklist. After **Research design** (or review/results),",
  "  decide whether the on-disk spine should change.",
  `- **Read** — intent unclear, aligning literature/writing/experiments, or user refers to direction:`,
  `  \`${TOOL_NAMES.researchBriefRead}\` (read to **align**, not to memorize).`,
  `- **Update** — user confirmed something worth keeping (direction tweak, sharpened claim, open question,`,
  `  methodology intuition): \`${TOOL_NAMES.researchBriefUpdate}\` — how-to on that tool.`,
  "- Never use generic edit/write on `.brief.md` — brief tools only.",
  "- The user may rewrite the whole file in **Files** anytime.",
  "",
  "### Judgment",
  "",
  "- Prefer **substance** over headings — missing sections are fine.",
  "- Do not treat the brief as completion gate (\"all sections full before X\").",
  "- If chat and brief disagree on **project intent**, the brief wins; ask before overwriting user prose.",
  "- Results **contradict** the brief → flag it; suggest **Research design** + brief revision before more runs.",
].join("\n");
