import { describe, expect, it, beforeEach, afterEach } from "vitest";
import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { promptManager } from "../../src/main/prompts";
import {
  PRISM_SYSTEM_FILE,
  syncProjectPromptFile,
} from "../../src/main/services/prompt-sync";
import { TOOL_NAMES } from "../../src/shared/tool-names";

describe("syncProjectPromptFile", () => {
  let projectRoot: string;

  beforeEach(() => {
    promptManager.invalidate();
    promptManager.initialize();
    projectRoot = mkdtempSync(join(tmpdir(), "prism-prompt-sync-"));
  });

  afterEach(() => {
    rmSync(projectRoot, { recursive: true, force: true });
  });

  it("writes composeStableSystem content without AGENTS.md or profile overlay", () => {
    syncProjectPromptFile(projectRoot, {
      agentsMdContent: "# User AGENTS\n\nCustom project note.",
      profileId: "review",
      profileInstructions: "Be thorough.",
      customRules: [{ name: "Tests", content: "Run pnpm test." }],
    });

    const raw = readFileSync(
      join(projectRoot, ".prismnext", "agent", PRISM_SYSTEM_FILE),
      "utf-8",
    );
    expect(raw).toContain("Generated by Prism");
    expect(raw).toContain("Citations & Bibliography");
    expect(raw).not.toContain("User AGENTS");
    expect(raw).not.toContain("Active Agent Profile");
    expect(raw).not.toContain("Run pnpm test");
    expect(raw).toContain("Chat paper citations");
    expect(raw).toContain(TOOL_NAMES.literatureStage);
    expect(raw).not.toContain("Prism Tools Guide");
    expect(raw).not.toContain("Reference & literature");
  });
});
