import { describe, expect, it, beforeEach, afterEach } from "vitest";
import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { promptManager } from "../../src/main/prompts";
import {
  PRISM_SYSTEM_FILE,
  syncProjectPromptFile,
} from "../../src/main/services/prompt-sync";

describe("syncProjectPromptFile", () => {
  let projectRoot: string;

  beforeEach(() => {
    promptManager.invalidate();
    promptManager.initialize();
    projectRoot = mkdtempSync(join(tmpdir(), "prism-prompt-sync-"));
  });

  afterEach(() => {
    rmSync(projectRoot, { recursive: true, force: true });
  });

  it("writes composeStableSystem baseline only (Plan A — no profile modules)", () => {
    syncProjectPromptFile(projectRoot, {
      agentsMdContent: "# User AGENTS\n\nCustom project note.",
      customRules: [{ name: "Tests", content: "Run pnpm test." }],
      workspaceDirs: [{ function: "manuscript", name: "manuscript", mainTex: "main.tex" }],
    });

    const raw = readFileSync(
      join(projectRoot, ".prismnext", "agent", PRISM_SYSTEM_FILE),
      "utf-8",
    );
    expect(raw).toContain("Generated by Prism");
    expect(raw).toContain("Prism Assistant");
    expect(raw).not.toContain("User AGENTS");
    expect(raw).not.toContain("Active Agent Profile");
    expect(raw).not.toContain("Run pnpm test");
    expect(raw).not.toContain("Chat paper citations");
    expect(raw).not.toContain("Citations & Bibliography");
    expect(raw).not.toContain("Academic Writing");
  });
});
