import { readdir, readFile, stat } from "node:fs/promises";
import { join, relative } from "node:path";
import { existsSync } from "node:fs";
import { IGNORED_DIRECTORY_NAMES } from "./filesystem";

const SCAFFOLD_IGNORE_DIRS = new Set([
  ...IGNORED_DIRECTORY_NAMES,
  ".git",
  ".prismnext",
  "dist",
  "out",
  "build",
  ".next",
  "coverage",
  "target",
  "vendor",
  ".turbo",
  ".cache",
  ".superpowers",
  "__pycache__",
]);

const KEY_CONFIG_FILES = [
  "package.json",
  "pnpm-lock.yaml",
  "package-lock.json",
  "README.md",
  "tsconfig.json",
  "electron.vite.config.ts",
  "electron-builder.yml",
  "pyproject.toml",
  "Cargo.toml",
  "go.mod",
  ".gitignore",
];

const MAX_TREE_DEPTH = 3;
const MAX_TREE_ENTRIES = 80;
const README_EXCERPT_LINES = 40;

export interface AgentsMdScaffoldResult {
  agentsMdPath: string;
  content: string;
  digestMarkdown: string;
  updated: boolean;
  stats: { dirsListed: number; filesListed: number };
}

interface TreeLine {
  path: string;
  depth: number;
  isDir: boolean;
}

async function listTree(
  root: string,
  current: string,
  depth: number,
  lines: TreeLine[],
): Promise<void> {
  if (depth > MAX_TREE_DEPTH || lines.length >= MAX_TREE_ENTRIES) return;

  let entries: string[];
  try {
    entries = await readdir(current);
  } catch {
    return;
  }

  entries.sort((a, b) => a.localeCompare(b));

  for (const name of entries) {
    if (lines.length >= MAX_TREE_ENTRIES) break;
    if (name.startsWith(".") && name !== ".github") continue;

    const abs = join(current, name);
    const rel = relative(root, abs).replace(/\\/g, "/");
    let isDir = false;
    try {
      isDir = (await stat(abs)).isDirectory();
    } catch {
      continue;
    }

    if (isDir) {
      if (SCAFFOLD_IGNORE_DIRS.has(name)) continue;
      lines.push({ path: `${rel}/`, depth, isDir: true });
      await listTree(root, abs, depth + 1, lines);
    } else if (depth <= MAX_TREE_DEPTH) {
      lines.push({ path: rel, depth, isDir: false });
    }
  }
}

function formatTree(lines: TreeLine[]): string {
  if (lines.length === 0) return "(empty or unreadable)";
  return lines
    .map((line) => `${"  ".repeat(line.depth)}${line.isDir ? line.path : line.path}`)
    .join("\n");
}

async function readPackageSummary(projectRoot: string): Promise<string[]> {
  const pkgPath = join(projectRoot, "package.json");
  if (!existsSync(pkgPath)) return [];
  try {
    const pkg = JSON.parse(await readFile(pkgPath, "utf-8")) as Record<string, unknown>;
    const lines: string[] = [];
    if (typeof pkg.name === "string") lines.push(`- **Name:** ${pkg.name}`);
    if (typeof pkg.description === "string" && pkg.description.trim()) {
      lines.push(`- **Description:** ${pkg.description.trim()}`);
    }
    if (typeof pkg.version === "string") lines.push(`- **Version:** ${pkg.version}`);
    const scripts = pkg.scripts as Record<string, string> | undefined;
    if (scripts && Object.keys(scripts).length > 0) {
      lines.push("", "### Scripts", "");
      for (const [key, cmd] of Object.entries(scripts).slice(0, 12)) {
        lines.push(`- \`${key}\` → \`${cmd}\``);
      }
    }
    return lines;
  } catch {
    return ["- (could not parse package.json)"];
  }
}

async function readReadmeExcerpt(projectRoot: string): Promise<string | null> {
  for (const name of ["README.md", "readme.md", "Readme.md"]) {
    const p = join(projectRoot, name);
    if (!existsSync(p)) continue;
    try {
      const lines = (await readFile(p, "utf-8")).split("\n").slice(0, README_EXCERPT_LINES);
      const text = lines.join("\n").trim();
      if (text) return text;
    } catch { /* next */ }
  }
  return null;
}

function detectProjectKind(projectRoot: string): string[] {
  const hints: string[] = [];
  if (existsSync(join(projectRoot, "package.json"))) {
    if (existsSync(join(projectRoot, "electron.vite.config.ts"))) {
      hints.push("Electron + Vite desktop app");
    } else if (existsSync(join(projectRoot, "next.config.ts")) || existsSync(join(projectRoot, "next.config.js"))) {
      hints.push("Next.js web app");
    } else {
      hints.push("Node.js / TypeScript project");
    }
  }
  if (existsSync(join(projectRoot, "pyproject.toml"))) hints.push("Python project");
  if (existsSync(join(projectRoot, "Cargo.toml"))) hints.push("Rust project");
  if (existsSync(join(projectRoot, "go.mod"))) hints.push("Go project");
  const texCount = existsSync(join(projectRoot, "main.tex")) || existsSync(join(projectRoot, "manuscript"));
  if (texCount) hints.push("LaTeX manuscript workspace");
  return hints;
}

export function renderAgentsMdFromDigest(parts: {
  projectRoot: string;
  projectHints: string[];
  packageLines: string[];
  treeText: string;
  configFiles: string[];
  readmeExcerpt: string | null;
  existingNote: string | null;
}): string {
  const sections: string[] = [
    "# Project Instructions (AGENTS.md)",
    "",
    "> Auto-generated by prismnext `/setup`. Edit freely — injected as **Project Instructions** into every AI chat for this project.",
    "",
    "## Overview",
    "",
  ];

  if (parts.projectHints.length > 0) {
    sections.push(...parts.projectHints.map((h) => `- ${h}`), "");
  } else {
    sections.push("- Add a one-line summary of what this project does.", "");
  }

  if (parts.packageLines.length > 0) {
    sections.push("## Package", "", ...parts.packageLines, "");
  }

  sections.push(
    "## Directory layout",
    "",
    "High-level tree (build artifacts and dependencies omitted):",
    "",
    "```text",
    parts.treeText,
    "```",
    "",
  );

  if (parts.configFiles.length > 0) {
    sections.push("## Key config files", "", ...parts.configFiles.map((f) => `- \`${f}\``), "");
  }

  if (parts.readmeExcerpt) {
    sections.push(
      "## README excerpt",
      "",
      parts.readmeExcerpt,
      "",
      parts.readmeExcerpt.length >= 2000 ? "_(truncated)_" : "",
      "",
    );
  }

  sections.push(
    "## Working conventions",
    "",
    "- Scale edits to the task — read a file before changing it; keep changes coherent with the surrounding structure.",
    "- Match existing naming, import style, and test patterns in this repo.",
    "- Do not modify generated/build output unless explicitly asked.",
    "",
    "## Commands",
    "",
    "Use the package scripts above for install, dev, test, and build when applicable.",
    "",
    "## Boundaries",
    "",
    "- `.workbench/` — project id, compile cache, and agent config (this file).",
    "- Do not commit secrets or API keys.",
    "",
  );

  if (parts.existingNote) {
    sections.push("<!--", parts.existingNote, "-->", "");
  }

  return sections.join("\n").replace(/\n{3,}/g, "\n\n").trimEnd() + "\n";
}

/** Build AGENTS.md content from a fast local survey (no AI). */
export async function buildAgentsMdScaffold(projectRoot: string): Promise<AgentsMdScaffoldResult> {
  const agentsMdPath = join(projectRoot, ".workbench", "agent", "AGENTS.md");
  const updated = existsSync(agentsMdPath);

  const treeLines: TreeLine[] = [];
  await listTree(projectRoot, projectRoot, 0, treeLines);
  const treeText = formatTree(treeLines);

  const configFiles = KEY_CONFIG_FILES.filter((f) => existsSync(join(projectRoot, f)));
  const packageLines = await readPackageSummary(projectRoot);
  const readmeExcerpt = await readReadmeExcerpt(projectRoot);
  const projectHints = detectProjectKind(projectRoot);

  const digestMarkdown = [
    "## Project digest",
    "",
    ...projectHints.map((h) => `- ${h}`),
    "",
    "### Tree",
    "```text",
    treeText,
    "```",
    "",
    ...(packageLines.length ? ["### Package", "", ...packageLines, ""] : []),
    ...(configFiles.length ? ["### Config files", ...configFiles.map((f) => `- ${f}`), ""] : []),
    ...(readmeExcerpt ? ["### README excerpt", readmeExcerpt.slice(0, 3000), ""] : []),
  ].join("\n");

  const content = renderAgentsMdFromDigest({
    projectRoot,
    projectHints,
    packageLines,
    treeText,
    configFiles,
    readmeExcerpt,
    existingNote: updated ? "Previously existed — scaffold refreshed on " + new Date().toISOString() : null,
  });

  return {
    agentsMdPath,
    content,
    digestMarkdown,
    updated,
    stats: {
      dirsListed: treeLines.filter((l) => l.isDir).length,
      filesListed: treeLines.filter((l) => !l.isDir).length,
    },
  };
}
