import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { promptManager } from "../prompts";
import type { PromptContext } from "../prompts/types";

export const PRISM_SYSTEM_FILE = "_prism-system.md";
export const PRISM_AGENTS_REL = ".prismnext/agent/AGENTS.md";
export const PRISM_SYSTEM_REL = ".prismnext/agent/_prism-system.md";

/** Paths relative to session cwd — OpenCode `instructions` array entries. */
export const PRISM_OPENCODE_INSTRUCTIONS = [
  PRISM_AGENTS_REL,
  PRISM_SYSTEM_REL,
] as const;

const PRISM_AGENT_GITIGNORE_LINES = [
  ".prismnext/agent/_prism-system.md",
  ".prismnext/agent/_*.md",
];

const GENERATED_HEADER =
  "<!-- Generated by Prism Next — do not edit. Toggle modules in Settings → Prompts & Rules. -->\n\n";

/** Keep generated prompt artifacts out of git when the project uses git. */
export function ensurePrismGeneratedPromptGitignored(projectRoot: string): void {
  // Only touch root .gitignore after the user has initialized git.
  if (!existsSync(join(projectRoot, ".git"))) return;
  const gitignorePath = join(projectRoot, ".gitignore");
  let content = "";
  if (existsSync(gitignorePath)) {
    try {
      content = readFileSync(gitignorePath, "utf-8");
    } catch {
      return;
    }
  }
  const missing = PRISM_AGENT_GITIGNORE_LINES.filter((line) => !content.includes(line));
  if (missing.length === 0) return;

  const prefix = content.length > 0 && !content.endsWith("\n") ? "\n" : "";
  const block =
    "\n# Prism Next generated agent prompts (managed by the app, not project source)\n" +
    missing.join("\n") +
    "\n";
  writeFileSync(gitignorePath, content + prefix + block, "utf-8");
}

/**
 * Write stable system layers to `.prismnext/agent/_prism-system.md`.
 * AGENTS.md is loaded separately via OpenCode `instructions`.
 */
export function syncProjectPromptFile(projectRoot: string, ctx: PromptContext): void {
  const agentDir = join(projectRoot, ".prismnext", "agent");
  mkdirSync(agentDir, { recursive: true });
  ensurePrismGeneratedPromptGitignored(projectRoot);

  const content = promptManager.composeStableSystem(ctx);
  const body = content.trim() ? `${GENERATED_HEADER}${content.trim()}\n` : `${GENERATED_HEADER}\n`;
  writeFileSync(join(agentDir, PRISM_SYSTEM_FILE), body, "utf-8");
}

/** Merge OpenCode `instructions` into app-level config. Returns whether paths changed. */
export function mergeOpencodeInstructions(
  config: Record<string, unknown>,
): { config: Record<string, unknown>; changed: boolean } {
  const desired = [...PRISM_OPENCODE_INSTRUCTIONS];
  const existing = config.instructions;
  const existingList = Array.isArray(existing)
    ? existing.map(String)
    : typeof existing === "string"
      ? [existing]
      : [];

  const changed =
    existingList.length !== desired.length
    || desired.some((path, i) => existingList[i] !== path);

  if (!changed) {
    return { config, changed: false };
  }

  return {
    config: { ...config, instructions: desired },
    changed: true,
  };
}
