import { TOOL_NAMES } from "../../../../shared/agent/tool-names";

/**
 * Local Office / PDF / EPUB documents — when/边界；how-to 在 document-read.
 * Library paper PDFs → literature-library. Public URLs → web-research.
 */
export const OFFICE_DOCUMENTS_PROMPT = [
  "## Local documents (Office, PDF & related)",
  "",
  "Project files that are **Word, PowerPoint, Excel, OpenDocument, RTF, EPUB, CSV, or PDF** — convert to Markdown",
  "with the document-read tool instead of guessing from a binary or unzipping the package.",
  "",
  "### Scope boundary",
  "",
  "- **This module** — local files on disk in the current project / worktree that match those formats",
  "  (drafts, slides, spreadsheets, attached PDFs, EPUB notes).",
  "- **Project literature library** — papers already in the library, cited as `[@bibkey]`.",
  "  Intensive-reading PDF body text stays on literature-read-pdf (MinerU), not document-read.",
  "- **Web research** — public URLs. Do not webfetch a local path.",
  "- **Source files** — `.md`, `.tex`, `.typ`, `.py`, and other text → read / grep.",
  "",
  "### Composer vs tool",
  "",
  "- If this turn already includes converted attachment Markdown (`[DOCX attachment: …]` or similar),",
  "  **answer from that text**. Do not explore the repo to guess a different file.",
  "- Composer attachments may be outside the project; do not call document-read on those paths.",
  "- document-read is for a **project / worktree path** when you need a fresh read or a query filter.",
  "",
  "### Honesty",
  "",
  "- No converted attachment Markdown and no successful document-read for that file → **say you cannot read it**.",
  "  Do not invent the document. Do not present another project file as the attachment.",
  "",
  "### When this applies",
  "",
  "- The user @-mentions, attaches, or names a `.docx`, `.pptx`, `.xlsx`, `.pdf`, `.epub`, `.csv`, or similar file.",
  "- You need headings, tables, or slide text from an Office / OpenDocument file in the repo.",
  "- A non-library PDF in the project should be read as Markdown (methods notes, reports, drafts).",
  "",
  "### When not to use document-read",
  "",
  "- The PDF is a **library paper** on the intensive-reading list → literature-read-pdf.",
  "- The file is already Markdown / LaTeX / Typst / code → read / grep.",
  "- The user asked to **write** or export a Word/PPTX file — there is no document-write tool.",
  "- A scanned PDF fails conversion — suggest adding it to the literature library for MinerU, or a text copy.",
  "- The user attached an Office/PDF file — do **not** substitute another manuscript in the project",
  "  (`.typ`, `.tex`, `.md`) just because it is easier to read.",
  "",
  "### Route the request",
  "",
  "1. **This turn already has attachment Markdown?** — use it. Do not ls/read a substitute.",
  "2. **Library paper PDF?** — intensive-reading list + bibkey →",
  `   \`${TOOL_NAMES.literatureReadPdf}\`.`,
  "3. **Local whitelist document in the project?** →",
  `   \`${TOOL_NAMES.documentRead}\` (how-to on that tool).`,
  "4. **Public URL?** → web research tools, not a file path.",
].join("\n");
