import type { ShortcutDef } from "./types";

/** Canonical shortcut definitions — single source of truth for defaults. */
export const SHORTCUT_REGISTRY: readonly ShortcutDef[] = [
  // ── shell (fixed) ──
  {
    id: "shell.newWindow",
    category: "shell",
    remappable: false,
    scope: "app",
    defaultChord: { key: "n", primary: true },
    labelKey: "shortcuts.shell.newWindow",
    menuAccelerator: true,
    implemented: true,
  },
  {
    id: "shell.close",
    category: "shell",
    remappable: false,
    scope: "app",
    defaultChord: { key: "w", primary: true },
    labelKey: "shortcuts.shell.close",
    menuAccelerator: true,
    implemented: true,
  },
  {
    id: "shell.closeWindow",
    category: "shell",
    remappable: false,
    scope: "app",
    defaultChord: { key: "w", primary: true, shift: true },
    labelKey: "shortcuts.shell.closeWindow",
    menuAccelerator: true,
    implemented: true,
  },
  {
    id: "shell.saveFile",
    category: "shell",
    remappable: false,
    scope: "app",
    defaultChord: { key: "s", primary: true },
    labelKey: "shortcuts.shell.saveFile",
    implemented: true,
  },
  {
    id: "shell.toggleLeftSidebar",
    category: "shell",
    remappable: false,
    scope: "app",
    defaultChord: { key: "b", primary: true },
    labelKey: "shortcuts.shell.toggleLeftSidebar",
    implemented: true,
  },
  {
    id: "shell.toggleRightArea",
    category: "shell",
    remappable: false,
    scope: "app",
    defaultChord: { key: "b", primary: true, alt: true },
    labelKey: "shortcuts.shell.toggleRightArea",
    implemented: true,
  },
  {
    id: "shell.toggleRightAreaMaximize",
    category: "shell",
    remappable: false,
    scope: "app",
    defaultChord: { key: "b", primary: true, ctrl: true },
    labelKey: "shortcuts.shell.toggleRightAreaMaximize",
    implemented: true,
  },
  {
    id: "shell.openSettings",
    category: "shell",
    remappable: false,
    scope: "app",
    defaultChord: { key: ",", primary: true },
    labelKey: "shortcuts.shell.openSettings",
    implemented: true,
  },
  {
    id: "shell.commandPalette",
    category: "shell",
    remappable: false,
    scope: "app",
    defaultChord: { key: "k", primary: true },
    labelKey: "shortcuts.shell.commandPalette",
    implemented: true,
  },

  // ── editor (fixed; handlers in editor host) ──
  {
    id: "editor.find",
    category: "editor",
    remappable: false,
    scope: "editor",
    defaultChord: { key: "f", primary: true },
    labelKey: "shortcuts.editor.find",
    implemented: true,
  },
  {
    id: "editor.bold",
    category: "editor",
    remappable: false,
    scope: "editor",
    defaultChord: { key: "b", primary: true },
    labelKey: "shortcuts.editor.bold",
    implemented: true,
  },
  {
    id: "editor.italic",
    category: "editor",
    remappable: false,
    scope: "editor",
    defaultChord: { key: "i", primary: true },
    labelKey: "shortcuts.editor.italic",
    implemented: true,
  },
  {
    id: "editor.comment",
    category: "editor",
    remappable: false,
    scope: "editor",
    defaultChord: { key: "/", primary: true },
    labelKey: "shortcuts.editor.comment",
    implemented: true,
  },
  {
    id: "editor.closeSearch",
    category: "editor",
    remappable: false,
    scope: "editor",
    defaultChord: { key: "Escape" },
    labelKey: "shortcuts.editor.closeSearch",
    implemented: true,
  },

  // ── workspace (remappable later) ──
  {
    id: "workspace.nextTab",
    category: "workspace",
    remappable: true,
    scope: "right-area",
    defaultChord: { key: "Tab", primary: true },
    labelKey: "shortcuts.workspace.nextTab",
    implemented: true,
  },
  {
    id: "workspace.prevTab",
    category: "workspace",
    remappable: true,
    scope: "right-area",
    defaultChord: { key: "Tab", primary: true, shift: true },
    labelKey: "shortcuts.workspace.prevTab",
    implemented: true,
  },
  {
    id: "workspace.gitRefresh",
    category: "workspace",
    remappable: true,
    scope: "right-area",
    defaultChord: { key: "r", primary: true },
    labelKey: "shortcuts.workspace.gitRefresh",
    implemented: true,
  },
  {
    id: "workspace.insertToChat",
    category: "workspace",
    remappable: true,
    scope: "app",
    // ⌥L / Alt+L — also bound by CodeMirrorInsertHost, TerminalInsertHost,
    // and GitDiffInsertHost (capture-phase). ⌘L / Ctrl+L is taken by
    // product.cycleMessageWidth.
    defaultChord: { key: "l", alt: true },
    labelKey: "shortcuts.workspace.insertToChat",
    implemented: true,
  },
  // Mode navigation: Control+1–6 on all platforms (+ Shift = maximize).
  // Avoids macOS screenshot chords (⌘⇧3/4/5). Templates: no shortcut.
  // workspace.openTexWorkspace* ids are kept so custom chords still open Files.
  {
    id: "workspace.openTexWorkspace",
    category: "workspace",
    remappable: true,
    scope: "app",
    defaultChord: { key: "1", ctrl: true },
    labelKey: "shortcuts.workspace.openTexWorkspace",
    implemented: true,
  },
  {
    id: "workspace.openTexWorkspaceMaximize",
    category: "workspace",
    remappable: true,
    scope: "app",
    defaultChord: { key: "1", ctrl: true, shift: true },
    labelKey: "shortcuts.workspace.openTexWorkspaceMaximize",
    implemented: true,
  },
  {
    id: "workspace.openLiterature",
    category: "workspace",
    remappable: true,
    scope: "app",
    defaultChord: { key: "2", ctrl: true },
    labelKey: "shortcuts.workspace.openLiterature",
    implemented: true,
  },
  {
    id: "workspace.openLiteratureMaximize",
    category: "workspace",
    remappable: true,
    scope: "app",
    defaultChord: { key: "2", ctrl: true, shift: true },
    labelKey: "shortcuts.workspace.openLiteratureMaximize",
    implemented: true,
  },
  {
    id: "workspace.openExperiments",
    category: "workspace",
    remappable: true,
    scope: "app",
    defaultChord: { key: "3", ctrl: true },
    labelKey: "shortcuts.workspace.openExperiments",
    implemented: true,
  },
  {
    id: "workspace.openExperimentsMaximize",
    category: "workspace",
    remappable: true,
    scope: "app",
    defaultChord: { key: "3", ctrl: true, shift: true },
    labelKey: "shortcuts.workspace.openExperimentsMaximize",
    implemented: true,
  },
  {
    id: "workspace.openFiles",
    category: "workspace",
    remappable: true,
    scope: "app",
    defaultChord: { key: "4", ctrl: true },
    labelKey: "shortcuts.workspace.openFiles",
    implemented: true,
  },
  {
    id: "workspace.openFilesMaximize",
    category: "workspace",
    remappable: true,
    scope: "app",
    defaultChord: { key: "4", ctrl: true, shift: true },
    labelKey: "shortcuts.workspace.openFilesMaximize",
    implemented: true,
  },
  {
    id: "workspace.openGit",
    category: "workspace",
    remappable: true,
    scope: "app",
    defaultChord: { key: "5", ctrl: true },
    labelKey: "shortcuts.workspace.openGit",
    implemented: true,
  },
  {
    id: "workspace.openGitMaximize",
    category: "workspace",
    remappable: true,
    scope: "app",
    defaultChord: { key: "5", ctrl: true, shift: true },
    labelKey: "shortcuts.workspace.openGitMaximize",
    implemented: true,
  },
  {
    id: "workspace.openBrowser",
    category: "workspace",
    remappable: true,
    scope: "app",
    defaultChord: { key: "6", ctrl: true },
    labelKey: "shortcuts.workspace.openBrowser",
    implemented: true,
  },
  {
    id: "workspace.openBrowserMaximize",
    category: "workspace",
    remappable: true,
    scope: "app",
    defaultChord: { key: "6", ctrl: true, shift: true },
    labelKey: "shortcuts.workspace.openBrowserMaximize",
    implemented: true,
  },
  {
    id: "workspace.openTerminal",
    category: "workspace",
    remappable: true,
    scope: "app",
    defaultChord: { key: "`", ctrl: true },
    labelKey: "shortcuts.workspace.openTerminal",
    implemented: true,
  },
  {
    id: "workspace.openTerminalMaximize",
    category: "workspace",
    remappable: true,
    scope: "app",
    defaultChord: { key: "`", ctrl: true, shift: true },
    labelKey: "shortcuts.workspace.openTerminalMaximize",
    implemented: true,
  },

  // ── product (remappable later) ──
  {
    id: "product.focusAiBar",
    category: "product",
    // Same chord as editor.italic: CM wins when editor focused; else focus chat
    // composer (panel) or AiBar capsule when editor is maximized.
    remappable: false,
    scope: "app",
    defaultChord: { key: "i", primary: true },
    labelKey: "shortcuts.product.focusAiBar",
    implemented: true,
  },
  {
    id: "product.newChat",
    category: "product",
    remappable: true,
    scope: "chat",
    defaultChord: { key: "t", primary: true },
    labelKey: "shortcuts.product.newChat",
    implemented: true,
  },
  {
    id: "product.nextChat",
    category: "product",
    remappable: true,
    scope: "chat",
    defaultChord: { key: "Tab", ctrl: true },
    labelKey: "shortcuts.product.nextChat",
    implemented: true,
  },
  {
    id: "product.prevChat",
    category: "product",
    remappable: true,
    scope: "chat",
    defaultChord: { key: "Tab", ctrl: true, shift: true },
    labelKey: "shortcuts.product.prevChat",
    implemented: true,
  },
  {
    id: "product.compile",
    category: "product",
    remappable: true,
    scope: "app",
    defaultChord: { key: "Enter", primary: true },
    labelKey: "shortcuts.product.compile",
    implemented: true,
  },
  {
    id: "product.acceptChange",
    category: "product",
    remappable: true,
    scope: "app",
    defaultChord: { key: "y", primary: true },
    labelKey: "shortcuts.product.acceptChange",
    implemented: true,
  },
  {
    id: "product.rejectChange",
    category: "product",
    remappable: true,
    scope: "app",
    defaultChord: { key: "n", primary: true },
    labelKey: "shortcuts.product.rejectChange",
    implemented: true,
  },
  {
    id: "product.acceptAll",
    category: "product",
    remappable: true,
    scope: "app",
    defaultChord: { key: "y", primary: true, shift: true },
    labelKey: "shortcuts.product.acceptAll",
    implemented: true,
  },
  {
    id: "product.rejectAll",
    category: "product",
    remappable: true,
    scope: "app",
    defaultChord: { key: "n", primary: true, shift: true },
    labelKey: "shortcuts.product.rejectAll",
    implemented: true,
  },
  {
    id: "product.togglePlanMode",
    category: "product",
    remappable: true,
    scope: "app",
    defaultChord: { key: "p", alt: true },
    labelKey: "shortcuts.product.togglePlanMode",
    implemented: true,
  },
  {
    id: "product.openModelPicker",
    category: "product",
    remappable: true,
    scope: "app",
    // ⌥K / Alt+K — ⌘K / Ctrl+K is command palette.
    defaultChord: { key: "k", alt: true },
    labelKey: "shortcuts.product.openModelPicker",
    implemented: true,
  },
  {
    id: "product.cycleMessageWidth",
    category: "product",
    remappable: true,
    scope: "chat",
    // ⌘L / Ctrl+L — pairs physically with focus composer (⌘I / Ctrl+I).
    // (workspace.insertToChat is ⌥L / Alt+L.)
    defaultChord: { key: "l", primary: true },
    labelKey: "shortcuts.product.cycleMessageWidth",
    implemented: true,
  },
  {
    id: "product.undoRename",
    category: "product",
    remappable: true,
    scope: "app",
    defaultChord: { key: "z", primary: true },
    labelKey: "shortcuts.product.undoRename",
    implemented: true,
  },
  {
    id: "product.cycleThemePack",
    category: "product",
    remappable: true,
    scope: "app",
    // ⌥T / Alt+T — appearance theme pack cycle (pairs with cycleChatBackdrop).
    defaultChord: { key: "t", alt: true },
    labelKey: "shortcuts.product.cycleThemePack",
    implemented: true,
  },
  {
    id: "product.cycleChatBackdrop",
    category: "product",
    remappable: true,
    scope: "app",
    // ⌥B / Alt+B — chat backdrop style cycle.
    defaultChord: { key: "b", alt: true },
    labelKey: "shortcuts.product.cycleChatBackdrop",
    implemented: true,
  },
] as const;

const BY_ID = new Map(SHORTCUT_REGISTRY.map((d) => [d.id, d]));

export function getShortcutDef(id: string): ShortcutDef | undefined {
  return BY_ID.get(id);
}

export function listShortcuts(): readonly ShortcutDef[] {
  return SHORTCUT_REGISTRY;
}
