import { TOOL_NAMES } from "../../../../shared/agent/tool-names";

/**
 * General web lookup — when/边界；how-to 在 websearch / webfetch tools。
 * Library [@bibkey] → literature-library; external papers [n] → chat-citation-staging.
 */
export const WEB_RESEARCH_PROMPT = [
  "## Web research (docs, tools & data)",
  "",
  "**Live public-web knowledge** that supports research work but is **not** a citable paper in an academic catalog",
  "and **not** already in the project library — tooling docs, APIs, datasets, standards, portals, and the",
  "current web context around them. Research spans far more than PDFs; when the answer lives on the open web,",
  "route here instead of guessing from memory.",
  "",
  "### Scope boundary",
  "",
  "- **This module** — discover and read **non-paper** web sources: official docs, tutorials, changelogs,",
  "  README/issue threads, package and registry pages, dataset/model portals, API references, benchmarks,",
  "  standards, and similar **operational or domain knowledge** on the public internet.",
  "- **Project literature library** — papers already in the project; cite as `[@bibkey]` — not here.",
  "- **Chat paper citations** — external **papers** staged and cited as `[n]`; catalog discovery lives there.",
  "- **Local project files** — repo sources, configs, logs, and artifacts on disk → read/grep/bash first.",
  "- **Scholarly reasoning** (global) — critical judgment; does not replace looking up a live doc or API page.",
  "",
  "### What belongs on the open web (examples, not exhaustive)",
  "",
  "Treat the web as the source of **current, concrete, non-manuscript** facts you cannot reliably infer.",
  "Typical buckets in research work — any similar need counts:",
  "",
  "**Tooling & reproducibility** — install guides, CLI/API docs, version changelogs, migration notes,",
  "container images, environment pins, build flags, compiler/runtime quirks, and the like.",
  "",
  "**Packages & libraries** — PyPI/crates/npm/conda pages, README sections, usage examples, deprecation",
  "notices, and maintainer guidance for the stack the project actually uses.",
  "",
  "**Data, models & benchmarks** — dataset cards, download/terms pages, model hubs, leaderboard pages,",
  "schema dictionaries, and portal navigation when the user needs *where* or *how* to obtain something.",
  "",
  "**Methods infrastructure** — cloud/HPC docs, instrument or pipeline manuals, file-format specs, ontology",
  "or standard-body pages, regulatory/ethical guidance pages, and other reference sites that are not paper PDFs.",
  "",
  "**Domain & current context** — encyclopedic explainers, course notes, official blog posts, release",
  "announcements, competition or grant pages, policy updates, and other time-sensitive background that",
  "catalog search will not capture well.",
  "",
  "If the need is **citable academic metadata** (title, authors, DOI, abstract for related work) →",
  "**Chat paper citations** / `literature-discover`, not general web search as the primary path.",
  "",
  "### When this applies",
  "",
  "- User asks how to install, configure, call, or debug a tool, library, service, or API.",
  "- User needs the **latest** official behavior — release notes, breaking changes, pricing/limits, or",
  "  whether a feature still exists.",
  "- User asks where to download a public dataset, weights, or reference corpus, or how a portal is organized.",
  "- User compares similar tools, formats, or services and needs primary web sources, not stale recall.",
  "- User references a URL, error message, or product name that requires reading the live page.",
  "- Snippets from search are insufficient — you need the full page body to answer accurately.",
  "- A Task or prior turn surfaced URLs worth reading before advising on Methods, Experiments, or implementation.",
  "",
  "### When not to use the open web",
  "",
  "- The answer is likely **already in the repo** → read/grep first.",
  "- The user wants a **library bibkey** or in-project PDF → **Literature library** tools.",
  "- The user wants **papers to cite** in chat → **Chat paper citations** + `literature-discover`.",
  "- You only need to **run** something locally and the command is already in project scripts or rules.",
  "",
  "### Route the request",
  "",
  "Guidance in order; skip what the request does not need:",
  "",
  "1. **Local or library first?** — read/grep on disk; unsure library paper →",
  `   \`${TOOL_NAMES.literatureSearch}\` before the public web.`,
  "2. **Paper metadata or operational web fact?** — papers → **Chat paper citations**;",
  "   docs/data/API/tool pages → this module.",
  "3. **Discover, then read** — open-web topic → `websearch`; promising URL → `webfetch` for body text",
  "   (how-to on those tools).",
  "4. **Hand off paper landing pages** — if `webfetch` hits DOI/arXiv/publisher paper pages,",
  "   **Chat paper citations** owns staging — HTML is not a finished citation.",
  "",
  "### Search judgment (soft)",
  "",
  "- **Query like a researcher**, not a search engine: name the tool/version, error text, file format,",
  "  or task (\"install\", \"migrate\", \"rate limits\") — whatever discriminates the right official page.",
  "- Prefer **primary sources** (vendor docs, registry pages, standards bodies, official repos) over",
  "  random SEO summaries when both appear.",
  "- When the user’s goal is ambiguous, search once broadly, then narrow with domain filters or a sharper",
  "  follow-up query — do not stop at one generic snippet if precision matters.",
  "- Fetch when snippets disagree, omit version-specific detail, or hide tables/code the user needs.",
  "- Tie findings back to the research task: what changed, what command/path applies, what limitation blocks progress.",
  "",
  "### Judgment",
  "",
  "- Do not substitute web search for **design thinking** (**Research design**) or **empirical runs** (**Experiments**).",
  "- Do not treat blog posts as authoritative when official docs exist — cite the primary page in your reply.",
  `- Project library PDFs → \`${TOOL_NAMES.literatureReadPdf}\` — not webfetch.`,
  "- Project rules may name preferred sources or offline mirrors — defer to them when present.",
  "- Run web tools in this conversation when needed unless the user asks to delegate.",
].join("\n");
