import { PromptComposer } from "../composer";
import type { PromptLayer, PromptContext } from "../types";
import { createCorePersonaLayer } from "../stable/persona";
import { composeStableSystem as composeStableSystemBlocks } from "../stable";
import { createActiveModulesLayer } from "../layers/active-modules";
import { createAgentsMdLayer } from "../layers/agents-md";
import { createCustomRulesLayer } from "../layers/custom-rules";
import { ALL_MODULES } from "../modules";
import { createLogger } from "../../app/logger";
import { countPromptTokens } from "../../lib/token-estimate";

/** DJB2 — must stay in sync with PromptComposer fingerprint hashing. */
function djb2Hash(s: string): string {
  let hash = 5381;
  for (let i = 0; i < s.length; i++) {
    hash = ((hash << 5) + hash) + s.charCodeAt(i);
  }
  return (hash >>> 0).toString(36);
}

function staticModuleContentFingerprint(): string {
  return ALL_MODULES
    .filter((m) => m.prompt)
    .map((m) => `${m.key}=${djb2Hash(m.prompt!)}`)
    .join(",");
}

const log = createLogger("prompt-manager", "agent");

const PROJECT_RULES_LAYER_ID = "custom-rules";
const AGENTS_MD_LAYER_ID = "agents-md";

function toStablePromptContext(ctx: PromptContext): PromptContext {
  return { ...ctx };
}

const STABLE_SYSTEM_EXCLUDE_LAYERS = [
  PROJECT_RULES_LAYER_ID,
  AGENTS_MD_LAYER_ID,
];

class PromptManager {
  private composer = new PromptComposer();
  private initialized = false;

  /** Register all layers and modules. Idempotent -- safe to call multiple times. */
  initialize(): void {
    if (this.initialized) return;

    this.composer.register(createCorePersonaLayer());
    this.composer.register(createAgentsMdLayer());
    this.composer.register(createActiveModulesLayer());
    this.composer.register(createCustomRulesLayer());
    this.composer.preComputeStatic();

    this.initialized = true;
    log.info(`PromptManager initialized (${this.composer.getLayers().length} layers)`);
  }

  compose(ctx: PromptContext): string {
    this.initialize();
    return this.composer.compose(ctx);
  }

  composeBase(ctx: PromptContext): string {
    this.initialize();
    return this.composer.compose(ctx, { excludeLayerIds: [PROJECT_RULES_LAYER_ID] });
  }

  /**
   * Stable system content passed to the Pi ResourceLoader in memory.
   * Join lives in `stable/` — composer layers stay for fingerprint / full compose.
   */
  composeStableSystem(ctx: PromptContext): string {
    this.initialize();
    return composeStableSystemBlocks(toStablePromptContext(ctx));
  }

  composeProjectRules(ctx: PromptContext): string {
    this.initialize();
    return this.composer.compose(ctx, { onlyLayerIds: [PROJECT_RULES_LAYER_ID] });
  }

  getLayers(): readonly PromptLayer[] {
    this.initialize();
    return this.composer.getLayers();
  }

  getKnowledgeModuleCatalog(ctx: PromptContext = {}): Array<{
    key: string;
    label: string;
    description: string;
    source: string;
    autoGenerated?: boolean;
    profileOnly?: boolean;
    selectableInProfile: boolean;
    injectPath: string;
    contentPreview: string;
    charCount: number;
    tokenCount: number;
  }> {
    return ALL_MODULES.map((m) => {
      const text = m.build ? m.build(ctx) : m.prompt ?? "";
      const contentPreview = text.trim()
        || (m.autoGenerated
          ? "Generated from project workspace configuration when folders are defined."
          : "");
      const { tokenCount, charCount } = countPromptTokens(contentPreview);
      const injectPath = m.expertOnly
        ? "Expert/subagent system prompt only (auto-attached, not Team files)"
        : m.orchestratorOnly
          ? "Primary orchestrator system prompt only (auto-attached, not Team files)"
          : m.profileOnly
            ? "Orchestrator + expert system prompt (auto-attached, not Team files)"
            : "Pi system prompt (all sessions)";
      return {
        key: m.key,
        label: m.label,
        description: m.description,
        source: m.source,
        autoGenerated: m.autoGenerated,
        profileOnly: m.profileOnly,
        selectableInProfile: Boolean(m.profileOnly),
        injectPath,
        contentPreview,
        charCount,
        tokenCount,
      };
    });
  }

  setLayerEnabled(id: string, enabled: boolean): void {
    this.composer.setEnabled(id, enabled);
  }

  dumpLayerStates(): Record<string, boolean> {
    const result: Record<string, boolean> = {};
    for (const l of this.composer.getLayers()) {
      if (l.userToggleable) {
        result[l.id] = l.enabled;
      }
    }
    return result;
  }

  loadLayerStates(states: Record<string, boolean>): void {
    for (const [id, enabled] of Object.entries(states)) {
      if (id === "user-instructions") continue;
      this.composer.setEnabled(id, enabled);
    }
    this.composer.invalidate();
  }

  computePromptFingerprint(ctx: PromptContext): string {
    this.initialize();
    const stableCtx = toStablePromptContext(ctx);
    const base = this.composer.fingerprint(stableCtx, {
      excludeLayerIds: STABLE_SYSTEM_EXCLUDE_LAYERS,
    });
    const modContent = staticModuleContentFingerprint();
    return `${base}|${modContent}`;
  }

  invalidate(): void {
    this.composer.invalidate();
  }
}

/** Catalog, project rules, and fingerprint. Live join: `assemble` + `stable`. */
export const promptManager = new PromptManager();
