/**
 * Literature / Zotero / citation desktop port.
 * Forwards to `window.electronAPI` — do not redefine DTOs here.
 * Used by literature-store, citation-staging-store, and extract listeners.
 */

import { forwardDesktop } from "./forward";

export const literatureDesktop = {
  zoteroProbe: forwardDesktop("zoteroProbe"),
  zoteroGetProjectBinding: forwardDesktop("zoteroGetProjectBinding"),
  zoteroGetLastSync: forwardDesktop("zoteroGetLastSync"),
  zoteroSetProjectBinding: forwardDesktop("zoteroSetProjectBinding"),
  zoteroPullCollection: forwardDesktop("zoteroPullCollection"),
  zoteroPullCollections: forwardDesktop("zoteroPullCollections"),
  literatureListCollections: forwardDesktop("literatureListCollections"),
  literatureReadingList: forwardDesktop("literatureReadingList"),
  literatureListCollectionPaperIds: forwardDesktop("literatureListCollectionPaperIds"),
  literatureCreateCollection: forwardDesktop("literatureCreateCollection"),
  literatureUpdateCollection: forwardDesktop("literatureUpdateCollection"),
  literatureDeleteCollection: forwardDesktop("literatureDeleteCollection"),
  literatureAddPapersToCollection: forwardDesktop("literatureAddPapersToCollection"),
  literatureRemovePapersFromCollection: forwardDesktop("literatureRemovePapersFromCollection"),
  literatureSearch: forwardDesktop("literatureSearch"),
  literatureList: forwardDesktop("literatureList"),
  literatureGetPdfCacheStatus: forwardDesktop("literatureGetPdfCacheStatus"),
  literatureCreatePaper: forwardDesktop("literatureCreatePaper"),
  literatureUpdatePaper: forwardDesktop("literatureUpdatePaper"),
  literatureDeletePaper: forwardDesktop("literatureDeletePaper"),
  literatureImportToLocal: forwardDesktop("literatureImportToLocal"),
  literatureCreateFromIdentifier: forwardDesktop("literatureCreateFromIdentifier"),
  literatureCreateFromStagedCitation: forwardDesktop("literatureCreateFromStagedCitation"),
  literatureCancelStagedCitationAdd: forwardDesktop("literatureCancelStagedCitationAdd"),
  onLiteratureStagedAddProgress: forwardDesktop("onLiteratureStagedAddProgress"),
  literatureExportBibToFile: forwardDesktop("literatureExportBibToFile"),
  literatureCite: forwardDesktop("literatureCite"),
  literatureCitationHealth: forwardDesktop("literatureCitationHealth"),
  literatureMergeIntoProjectBib: forwardDesktop("literatureMergeIntoProjectBib"),
  literatureImportFromProjectBib: forwardDesktop("literatureImportFromProjectBib"),
  literatureIngestPdf: forwardDesktop("literatureIngestPdf"),
  literatureReadPdfBytes: forwardDesktop("literatureReadPdfBytes"),
  literatureApplyIdentifiers: forwardDesktop("literatureApplyIdentifiers"),
  literatureFetchAndApplyMetadata: forwardDesktop("literatureFetchAndApplyMetadata"),
  literatureDownloadPdf: forwardDesktop("literatureDownloadPdf"),
  literatureAttachLocalPdf: forwardDesktop("literatureAttachLocalPdf"),
  literatureImportBibTeX: forwardDesktop("literatureImportBibTeX"),
  literatureGetAnnotations: forwardDesktop("literatureGetAnnotations"),
  literatureSaveAnnotation: forwardDesktop("literatureSaveAnnotation"),
  literatureDeleteAnnotation: forwardDesktop("literatureDeleteAnnotation"),
  onLiteraturePdfDownloadProgress: forwardDesktop("onLiteraturePdfDownloadProgress"),
  onLiteraturePaperMaterialized: forwardDesktop("onLiteraturePaperMaterialized"),
  onLiteratureAiMetadataChanged: forwardDesktop("onLiteratureAiMetadataChanged"),
  literatureGetStorageStats: forwardDesktop("literatureGetStorageStats"),
  literaturePruneOrphanAttachments: forwardDesktop("literaturePruneOrphanAttachments"),
  literaturePickPdf: forwardDesktop("literaturePickPdf"),
  literaturePickBibTeX: forwardDesktop("literaturePickBibTeX"),
  literatureRegenerateAiMetadata: forwardDesktop("literatureRegenerateAiMetadata"),
  literatureEnsurePaperPdf: forwardDesktop("literatureEnsurePaperPdf"),
  literatureGetCitationNetwork: forwardDesktop("literatureGetCitationNetwork"),
  literatureGetCitationNetworkPage: forwardDesktop("literatureGetCitationNetworkPage"),
  zoteroListCollections: forwardDesktop("zoteroListCollections"),
  literatureResolveAbs: forwardDesktop("literatureResolveAbs"),
  literatureGet: forwardDesktop("literatureGet"),
};
