// prism-next/src/renderer/lib/editor-themes/prism-theme.ts

import { HighlightStyle, syntaxHighlighting } from "@codemirror/language";
import { tags } from "@lezer/highlight";
import type { Extension } from "@codemirror/state";

/**
 * Creates a Prism syntax highlighting extension that reads colors from
 * CSS custom properties. The colors are generated by generateThemeCSS()
 * and vary with app primary color and light/dark mode.
 *
 * Because HighlightStyle.define() evaluates colors at definition time,
 * we re-create the extension on each mode switch. The CSS variables
 * will have been updated by that point.
 */
export function createPrismHighlightStyle(): Extension {
  return syntaxHighlighting(
    HighlightStyle.define([
      { tag: tags.keyword, color: "var(--syntax-keyword)" },
      { tag: tags.comment, color: "var(--syntax-comment)" },
      { tag: tags.string, color: "var(--syntax-string)" },
      { tag: tags.number, color: "var(--syntax-number)" },
      { tag: tags.function(tags.variableName), color: "var(--syntax-function)" },
      { tag: tags.typeName, color: "var(--syntax-type)" },
      { tag: tags.tagName, color: "var(--syntax-tag)" },
      { tag: tags.operator, color: "var(--syntax-operator)" },
      { tag: tags.regexp, color: "var(--syntax-regexp)" },
      { tag: tags.bracket, color: "var(--syntax-bracket)" },
      { tag: tags.variableName, color: "var(--syntax-variable)" },
      { tag: tags.labelName, color: "var(--syntax-label)" },
      { tag: tags.literal, color: "var(--syntax-literal)" },
      { tag: tags.emphasis, color: "var(--syntax-emphasis)", fontStyle: "italic" },
      { tag: tags.strong, color: "var(--syntax-strong)", fontWeight: "bold" },
      { tag: tags.link, color: "var(--syntax-link)", textDecoration: "underline" },
      // Meta/formatting
      { tag: tags.meta, color: "var(--syntax-comment)" },
      { tag: tags.processingInstruction, color: "var(--syntax-keyword)" },
      // Headings
      { tag: tags.heading, color: "var(--syntax-keyword)", fontWeight: "bold" },
      // Deleted/inserted (diff markers) — text-decoration handled by diff-overrides.css
      { tag: tags.deleted, color: "var(--syntax-comment)" },
      { tag: tags.inserted, color: "var(--syntax-string)" },
    ])
  );
}
