import { registerFsHandlers } from "./fs";
import { registerCompileHandlers } from "./compile";
import { registerAgentHandlers } from "./agent";
import { registerSettingsHandlers } from "./settings";
import { registerBrowserHandlers } from "./browser";
import { registerTerminalHandlers } from "./terminal";
import { registerExecutionHandlers } from "./execution";
import { registerGitHandlers } from "./git";
import { registerWorktreeHandlers } from "./worktree";
import { installIpcHandlerErrorGuard, registerLogHandlers } from "./log";
import { registerThemeHandlers } from "./theme";
import { registerWorkspaceHandlers } from "./workspace";
import { registerCommandsHandlers } from "./commands";
import { registerSkillsHandlers } from "./skills";
import { registerRulesHandlers } from "./rules";
import { registerExpertsHandlers } from "./subagents";
import { registerShellHandlers } from "./shell";
import { registerLiteratureHandlers } from "./literature";
import { registerLiteratureExtractHandlers } from "./literature-extract";
import { registerBibliographyHandlers } from "./bibliography";
import { registerZoteroHandlers } from "./zotero";
import { registerUpdateHandlers } from "./update";
import { registerResearchBriefHandlers } from "./research-brief";
import { registerResearchPlanHandlers } from "./research-plan";
import { registerExperimentHandlers } from "./experiment";
import { registerProvenanceHandlers } from "./provenance";
import { registerMcpHandlers } from "./mcp";
import { registerInteractionHandlers } from "./interaction";
import { registerProLicenseHandlers } from "./pro-license";
import { registerPacksHandlers } from "./teams";
import { registerUserPacksHandlers } from "./user-teams";
import { registerProjectLifecycleHandlers } from "./project-lifecycle";
import { registerWorkbenchHandlers } from "./workbench";

export function registerIpcHandlers(): void {
  installIpcHandlerErrorGuard();
  registerProjectLifecycleHandlers();
  registerWorkbenchHandlers();
  registerFsHandlers();
  registerCompileHandlers();
  registerAgentHandlers();
  registerMcpHandlers();
  registerSettingsHandlers();
  registerProLicenseHandlers();
  registerBrowserHandlers();
  registerTerminalHandlers();
  registerExecutionHandlers();
  registerGitHandlers();
  registerWorktreeHandlers();
  registerLogHandlers();
  registerThemeHandlers();
  registerWorkspaceHandlers();
  registerCommandsHandlers();
  registerSkillsHandlers();
  registerRulesHandlers();
  registerExpertsHandlers();
  registerShellHandlers();
  registerLiteratureHandlers();
  registerLiteratureExtractHandlers();
  registerBibliographyHandlers();
  registerZoteroHandlers();
  registerUpdateHandlers();
  registerResearchBriefHandlers();
  registerResearchPlanHandlers();
  registerExperimentHandlers();
  registerProvenanceHandlers();
  registerInteractionHandlers();
  registerPacksHandlers();
  registerUserPacksHandlers();
}

/** Isolated OpenCode chat IPC is no longer registered. Window teardown is a no-op. */
export function disposeChat(): void {}
