// prism-next/src/main/prompts/index.ts

import { PromptComposer } from "./composer";
import type { PromptLayer, PromptModule, PromptContext } from "./types";
import { createCorePersonaLayer } from "./layers/core-persona";
import { createActiveModulesLayer } from "./layers/active-modules";
import { createAgentsMdLayer } from "./layers/agents-md";
import { createCustomRulesLayer } from "./layers/custom-rules";
import { CORE_PERSONA_PROMPT } from "./layers/core-persona";
import { ALL_MODULES } from "./modules";
import { createLogger } from "../services/logger";

/** ~4 chars per token — standard English approximation for breakdown UI. */
function charsToTokens(text: string): number {
  return Math.max(1, Math.round(text.length / 4));
}

/** DJB2 — must stay in sync with PromptComposer fingerprint hashing. */
function djb2Hash(s: string): string {
  let hash = 5381;
  for (let i = 0; i < s.length; i++) {
    hash = ((hash << 5) + hash) + s.charCodeAt(i);
  }
  return (hash >>> 0).toString(36);
}

function staticModuleContentFingerprint(): string {
  return ALL_MODULES
    .filter((m) => m.prompt)
    .map((m) => `${m.key}=${djb2Hash(m.prompt!)}`)
    .join(",");
}

const log = createLogger("prompt-manager", "agent");

const PROJECT_RULES_LAYER_ID = "custom-rules";
const AGENTS_MD_LAYER_ID = "agents-md";

/** Strip per-turn layers for stable system file generation. */
function toStablePromptContext(ctx: PromptContext): PromptContext {
  return { ...ctx };
}

const STABLE_SYSTEM_EXCLUDE_LAYERS = [
  PROJECT_RULES_LAYER_ID,
  AGENTS_MD_LAYER_ID,
];

class PromptManager {
  private composer = new PromptComposer();
  private initialized = false;

  /** Register all layers and modules. Idempotent -- safe to call multiple times. */
  initialize(): void {
    if (this.initialized) return;

    // Layer 0: Core persona (always on, never toggleable)
    this.composer.register(createCorePersonaLayer());

    // Layer 1: AGENTS.md — project rules (before generic modules)
    this.composer.register(createAgentsMdLayer());

    // Layer 2: Active modules (built-in toggles)
    this.composer.register(createActiveModulesLayer());

    // Layer 2.5: User custom rules
    this.composer.register(createCustomRulesLayer());

    // Precompute static layers (core-persona)
    this.composer.preComputeStatic();

    this.initialized = true;
    console.log("[prismnext] PromptManager initialized (4 layers, 4 modules)");
    log.info("PromptManager initialized");
  }

  // -----------------------------------------------------------------
  // Public API
  // -----------------------------------------------------------------

  /** Assemble the final prompt string from all enabled layers. */
  compose(ctx: PromptContext): string {
    this.initialize();
    return this.composer.compose(ctx);
  }

  /** Base system prompt without project rules (legacy — prefer composeStableSystem). */
  composeBase(ctx: PromptContext): string {
    this.initialize();
    return this.composer.compose(ctx, { excludeLayerIds: [PROJECT_RULES_LAYER_ID] });
  }

  /**
   * Stable system content written to `.prismnext/agent/_prism-system.md` and
   * loaded by OpenCode via `instructions`. Excludes AGENTS.md (separate file)
   * and project rules (per-turn user block).
   */
  composeStableSystem(ctx: PromptContext): string {
    this.initialize();
    return this.composer.compose(toStablePromptContext(ctx), {
      excludeLayerIds: STABLE_SYSTEM_EXCLUDE_LAYERS,
    });
  }

  /** Project rules only — re-read from disk and injected on every chat turn. */
  composeProjectRules(ctx: PromptContext): string {
    this.initialize();
    return this.composer.compose(ctx, { onlyLayerIds: [PROJECT_RULES_LAYER_ID] });
  }

  /** Get all layers (for settings UI introspection). */
  getLayers(): readonly PromptLayer[] {
    this.initialize();
    return this.composer.getLayers();
  }

  /** Built-in knowledge module catalog (read-only — selection is per agent profile). */
  getKnowledgeModuleCatalog(ctx: PromptContext = {}): Array<{
    key: string;
    label: string;
    description: string;
    source: string;
    autoGenerated?: boolean;
    profileOnly?: boolean;
    selectableInProfile: boolean;
    injectPath: string;
    contentPreview: string;
  }> {
    return ALL_MODULES.map((m) => {
      const text = m.build ? m.build(ctx) : m.prompt ?? "";
      const injectPath = m.profileOnly
        ? "Orchestrator / Expert agent.md when selected in agent editor"
        : "Global `_prism-system.md` (OpenCode instructions — all sessions)";
      return {
        key: m.key,
        label: m.label,
        description: m.description,
        source: m.source,
        autoGenerated: m.autoGenerated,
        profileOnly: m.profileOnly,
        selectableInProfile: Boolean(m.profileOnly),
        injectPath,
        contentPreview: text.trim()
          || (m.autoGenerated
            ? "Generated from project workspace configuration when folders are defined."
            : ""),
      };
    });
  }

  /** Toggle a layer on/off. Only works for userToggleable layers. */
  setLayerEnabled(id: string, enabled: boolean): void {
    this.composer.setEnabled(id, enabled);
  }

  /** Export current layer toggle states for persistence. */
  dumpLayerStates(): Record<string, boolean> {
    const result: Record<string, boolean> = {};
    for (const l of this.composer.getLayers()) {
      if (l.userToggleable) {
        result[l.id] = l.enabled;
      }
    }
    return result;
  }

  /** Restore layer toggle states from persisted settings. */
  loadLayerStates(states: Record<string, boolean>): void {
    for (const [id, enabled] of Object.entries(states)) {
      if (id === "user-instructions") continue;
      this.composer.setEnabled(id, enabled);
    }
    this.composer.invalidate();
  }

  /** Estimate per-layer token counts for the context-window breakdown panel.
   *  Uses character-based estimation (1 token ≈ 4 chars) since we don't
   *  have a real tokenizer. OpenCode reports the true total — we only need
   *  approximate proportions for the visual breakdown.
   *
   *  Category mapping:
   *  - Custom system prompt → user-instructions (replaces core persona)
   *  - Default persona only → core-persona
   *  - custom-rules layer → project-rules (not modules)
   *
   *  Returns a map of category key → estimated token count. */
  estimateTokenBreakdown(ctx: PromptContext): Record<string, number> {
    this.initialize();
    const breakdown: Record<string, number> = {};

    const custom = ctx.userCustomPrompt?.trim();
    if (custom) {
      breakdown["user-instructions"] = charsToTokens(custom);
    } else {
      const coreLayer = this.composer.getLayers().find((l) => l.id === "core-persona");
      if (coreLayer?.enabled) {
        breakdown["core-persona"] = charsToTokens(CORE_PERSONA_PROMPT);
      }
    }

    const LAYER_TO_CATEGORY: Record<string, string> = {
      "active-modules": "modules",
      "custom-rules": "project-rules",
      "agents-md": "project-instructions",
    };

    for (const layer of this.composer.getLayers()) {
      if (layer.id === "core-persona") continue;
      if (!layer.enabled) continue;
      try {
        const text = layer.build(ctx);
        if (text) {
          const catKey = LAYER_TO_CATEGORY[layer.id] || layer.id;
          breakdown[catKey] = charsToTokens(text);
        }
      } catch {
        // Layer build failed — skip in breakdown
      }
    }

    return breakdown;
  }

  /** Stable fingerprint for `_prism-system.md` sync (excludes per-turn / per-tab layers). */
  computePromptFingerprint(ctx: PromptContext): string {
    this.initialize();
    const stableCtx = toStablePromptContext(ctx);
    const base = this.composer.fingerprint(stableCtx, {
      excludeLayerIds: STABLE_SYSTEM_EXCLUDE_LAYERS,
    });
    const modContent = staticModuleContentFingerprint();
    return `${base}|${modContent}`;
  }

  /** Invalidate all caches. Call when settings or project data changes. */
  invalidate(): void {
    this.composer.invalidate();
  }
}

/** Singleton -- the single entry point for all prompt assembly. */
export const promptManager = new PromptManager();
