// prism-next/src/main/prompts/types.ts

import type { WorkspaceFolder } from "../../shared/workbench/workspace-folder";

/** Context passed to dynamic prompt builders. */
export interface PromptContext {
  projectRoot?: string;
  workspaceDirs?: WorkspaceFolder[];
  agentsMdContent?: string;
  userCustomPrompt?: string;
  /** User-created custom rules (enabled only) */
  customRules?: Array<{ name: string; content: string }>;
  /** Module keys enabled for the current agent profile (e.g. ["citations"]). */
  profileModules?: string[];
  /** Profile module labels/descriptions for sibling modules (excludes proactive-scheduling). */
  profileModuleSummaries?: Array<{ key: string; label: string; description: string }>;
}

/** A single layer in the prompt stack. */
export interface PromptLayer {
  /** Unique identifier, e.g. "core-persona", "workspace-folders" */
  id: string;
  /** Ordering — lower numbers appear earlier in the final prompt */
  priority: number;
  /** Where this layer's content originates */
  source: "app" | "project" | "user" | "plugin";
  /** Can the user toggle this layer on/off? */
  userToggleable: boolean;
  /** Current enabled state */
  enabled: boolean;
  /** Whether this layer's build() returns the same result regardless of
   *  PromptContext. Static layers are precomputed once at registration time. */
  isStatic: boolean;
  /** Build this layer's prompt text. Return "" to skip. */
  build: (ctx: PromptContext) => string;
}

/** A content module that can be toggled on/off globally. */
export interface PromptModule {
  /** Unique key, e.g. "citations", "workspace-folders" */
  key: string;
  /** Human-readable label for the settings UI */
  label: string;
  /** Description shown in the settings UI */
  description: string;
  /** Global toggle state */
  enabled: boolean;
  /** Origin of this module */
  source: "app" | "project" | "plugin";
  /** When true, content is generated from app state (e.g. tool registry). */
  autoGenerated?: boolean;
  /** Static prompt text (mutually exclusive with build) */
  prompt?: string;
  /** Dynamic prompt builder (mutually exclusive with prompt) */
  build?: (ctx: PromptContext) => string;
  /** When true, inject only via orchestrator/expert profile — not global _prism-system. */
  profileOnly?: boolean;
  /** When true with profileOnly, inject only on the primary orchestrator — not experts/subagents. */
  orchestratorOnly?: boolean;
  /** When true with profileOnly, inject only on expert/subagent agent.md — not the primary orchestrator. */
  expertOnly?: boolean;
}
